'use client';
import { useEffect,useMemo,useState } from 'react';

type Assessment={id:string,participant_name:string,participant_contact:string|null,context:string|null,type:'behavioral'|'vocational',status:string,created_at:string,completed_at:string|null,token:string,result:any,deleted_at?:string|null,deletion_reason?:string|null};
export default function AdminClient(){
 const [items,setItems]=useState<Assessment[]>([]); const [name,setName]=useState(''); const [start,setStart]=useState(''); const [end,setEnd]=useState(''); const [form,setForm]=useState({participant_name:'',participant_contact:'',context:'',type:'behavioral'}); const [created,setCreated]=useState<string|null>(null); const [showDeleted,setShowDeleted]=useState(false);
 async function load(){const r=await fetch(`/api/assessments${showDeleted?'?deleted=1':''}`,{cache:'no-store'});if(r.ok)setItems(await r.json())}
 useEffect(()=>{load()},[showDeleted]);
 async function create(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/assessments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(r.ok){setCreated(d.url);setForm({participant_name:'',participant_contact:'',context:'',type:'behavioral'});load()}else alert(d.error||'Erro ao criar avaliação')}
 async function removeItem(x:Assessment){const reason=window.prompt('Motivo da exclusão (opcional):','Preenchimento incorreto');if(reason===null)return;if(!window.confirm(`Excluir o relatório de ${x.participant_name}? Ele irá para Relatórios excluídos e poderá ser restaurado.`))return;const r=await fetch('/api/assessments',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:x.id,reason})});const d=await r.json();if(!r.ok)return alert(d.error||'Não foi possível excluir.');load()}
 async function restoreItem(x:Assessment){const r=await fetch('/api/assessments',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:x.id,action:'restore'})});const d=await r.json();if(!r.ok)return alert(d.error||'Não foi possível restaurar.');load()}
 async function permanentlyDelete(x:Assessment){if(!window.confirm(`Excluir definitivamente ${x.participant_name}? Esta ação não poderá ser desfeita.`))return;const r=await fetch('/api/assessments',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:x.id,action:'permanent'})});const d=await r.json();if(!r.ok)return alert(d.error||'Não foi possível excluir definitivamente.');load()}
 const filtered=useMemo(()=>items.filter(x=>{const d=new Date(x.completed_at||x.created_at);const q=x.participant_name.toLowerCase().includes(name.toLowerCase());const a=!start||d>=new Date(start+'T00:00:00');const b=!end||d<=new Date(end+'T23:59:59.999');return q&&a&&b}),[items,name,start,end]);
 const done=items.filter(x=>x.status==='completed').length;
 const statusLabel=(s:string)=>s==='completed'?'Concluído':s==='started'?'Iniciado':s==='cancelled'?'Cancelado':'Pendente';
 return <main className="container grid">
  {!showDeleted&&<section className="grid grid-3"><div className="card"><div className="muted">Avaliações</div><div className="kpi">{items.length}</div></div><div className="card"><div className="muted">Concluídas</div><div className="kpi">{done}</div></div><div className="card"><div className="muted">Em aberto</div><div className="kpi">{items.length-done}</div></div></section>}
  {!showDeleted&&<section className="card"><h2 className="section-title">Criar avaliação</h2><form onSubmit={create} className="grid grid-2"><div><label className="label">Nome</label><input className="input" required value={form.participant_name} onChange={e=>setForm({...form,participant_name:e.target.value})}/></div><div><label className="label">Contato (opcional)</label><input className="input" value={form.participant_contact} onChange={e=>setForm({...form,participant_contact:e.target.value})}/></div><div><label className="label">Vaga, setor ou objetivo</label><input className="input" value={form.context} onChange={e=>setForm({...form,context:e.target.value})}/></div><div><label className="label">Tipo</label><select className="input" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="behavioral">Perfil comportamental</option><option value="vocational">Teste vocacional</option></select></div><div><button className="btn btn-primary">Gerar link individual</button></div></form>{created&&<div style={{marginTop:16,padding:14,background:'#f3f4f6',borderRadius:10}}><b>Link de uso único:</b><br/><span style={{wordBreak:'break-all'}}>{created}</span><div style={{marginTop:8}}><button className="btn btn-secondary" onClick={()=>navigator.clipboard.writeText(created)}>Copiar link</button></div></div>}</section>}
  <section className="card"><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><h2 className="section-title">{showDeleted?'Relatórios excluídos':'Histórico'}</h2><button className="btn btn-secondary" onClick={()=>setShowDeleted(v=>!v)}>{showDeleted?'Voltar ao histórico':'Ver relatórios excluídos'}</button></div><div className="grid grid-3" style={{marginBottom:16}}><div><label className="label">Pesquisar nome</label><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Nome da pessoa"/></div><div><label className="label">Data inicial</label><input className="input" type="date" value={start} onChange={e=>setStart(e.target.value)}/></div><div><label className="label">Data final</label><input className="input" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div></div><div style={{overflowX:'auto'}}><table><thead><tr><th>Nome</th><th>Tipo</th><th>Contexto</th><th>Status</th><th>Data</th>{showDeleted&&<th>Motivo</th>}<th>Ação</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td>{x.participant_name}</td><td>{x.type==='behavioral'?'Comportamental':'Vocacional'}</td><td>{x.context||'-'}</td><td><span className={'badge '+(x.status==='completed'?'ok':'')}>{statusLabel(x.status)}</span></td><td>{new Date(x.completed_at||x.created_at).toLocaleDateString('pt-BR')}</td>{showDeleted&&<td>{x.deletion_reason||'-'}</td>}<td>{showDeleted?<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn btn-secondary" onClick={()=>restoreItem(x)}>Restaurar</button><button className="btn btn-secondary" onClick={()=>permanentlyDelete(x)}>Excluir definitivamente</button></div>:<div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{x.status==='completed'?(x.type==='behavioral'?<><button className="btn btn-secondary" onClick={()=>openReport(x,'manager')}>Relatório gerencial</button><button className="btn btn-secondary" onClick={()=>openReport(x,'personal')}>Desenvolvimento pessoal</button></>:<button className="btn btn-secondary" onClick={()=>openReport(x,'vocational')}>Relatório / PDF</button>):<button className="btn btn-secondary" onClick={()=>navigator.clipboard.writeText(`${location.origin}/t/${x.token}`)}>Copiar link</button>}<button className="btn btn-secondary" onClick={()=>removeItem(x)}>Excluir</button></div>}</td></tr>)}</tbody></table></div></section>
 </main>
 function openReport(x:Assessment,mode:'manager'|'personal'|'vocational'){
  const w=window.open('','_blank');if(!w)return;const result=x.result||{};
  const title=x.type==='vocational'?'Relatório de Orientação Vocacional':mode==='manager'?'Relatório Gerencial de Perfil Comportamental':'Relatório de Desenvolvimento Pessoal';
  const rows=x.type==='behavioral'?behaviorDetailedRows(result,mode==='manager'?'manager':'personal'):vocRows(result);
  w.document.write(`<html><head><meta charset="utf-8"><title>${title} - ${escapeHtml(x.participant_name)}</title><style>body{font-family:Arial,sans-serif;padding:38px;color:#1f2937;line-height:1.5;max-width:900px;margin:auto}h1{color:#243a5a;margin-bottom:6px}h2{color:#243a5a;margin-top:0}h3{color:#334155;margin-bottom:6px}.sub{color:#64748b;margin-top:0}.box{border:1px solid #dfe3e8;border-radius:12px;padding:18px;margin:16px 0;page-break-inside:avoid}.item{border-top:1px solid #eceff3;padding-top:14px;margin-top:14px}.item:first-of-type{border-top:0;padding-top:0;margin-top:0}.score{font-weight:700;color:#243a5a}.callout{background:#f8fafc;border-left:4px solid #94a3b8;padding:12px 14px;margin:12px 0}.small{font-size:12px;color:#64748b}.note{font-size:12px;color:#666;margin-top:30px}ul{margin-top:6px;padding-left:20px}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #eee;padding:8px;text-align:left}@media print{button{display:none}body{padding:10px}.box{break-inside:avoid}}</style></head><body><h1>${title}</h1><p class="sub">Leitura explicada, item a item, dos resultados da avaliação.</p><p><b>Nome:</b> ${escapeHtml(x.participant_name)}<br/><b>Contexto:</b> ${escapeHtml(x.context||'-')}<br/><b>Data:</b> ${new Date(x.completed_at||x.created_at).toLocaleDateString('pt-BR')}</p>${rows}<div class="note">Este relatório é uma ferramenta de apoio ao autoconhecimento, desenvolvimento e conversas de gestão. Não constitui diagnóstico psicológico e não deve ser usado isoladamente para decisões de contratação, promoção, desligamento ou carreira. Resultados descrevem tendências declaradas no momento da avaliação e devem ser confrontados com comportamentos observáveis e contexto.</div><br/><button onclick="window.print()">Salvar / Imprimir PDF</button></body></html>`);w.document.close()
 }
}

const discInfo:any={
 D:{name:'Dominância',measures:'Ritmo de decisão, assertividade, iniciativa, foco em resultado e disposição para assumir controle diante de desafios.',high:'Tende a agir com rapidez, assumir decisões e buscar avanço. Pode demonstrar objetividade, competitividade e menor tolerância a demora.',mid:'Tende a alternar firmeza e cautela conforme o contexto. Consegue assumir a frente quando necessário, sem buscar controle o tempo todo.',low:'Tende a evitar confronto direto e decisões precipitadas, preferindo cooperação, consenso ou maior segurança antes de agir.',managerHigh:'Dê objetivos claros, autonomia dentro de limites e feedback objetivo. Evite microgerenciamento desnecessário. Observe impaciência, atropelo de etapas e escuta reduzida sob pressão.',managerLow:'Dê segurança para decidir, critérios claros e espaço para construir confiança. Observe adiamento de decisões difíceis e excesso de busca por concordância.',personalHigh:'Seu desafio é combinar velocidade com escuta, checagem e consideração do impacto das decisões sobre outras pessoas.',personalLow:'Seu desenvolvimento pode envolver maior assertividade, decisões com prazo definido e exposição gradual a situações de posicionamento.'},
 I:{name:'Influência',measures:'Expressividade, persuasão, entusiasmo, sociabilidade e tendência a mobilizar pessoas por meio da comunicação.',high:'Tende a se expressar com facilidade, criar conexão rapidamente e envolver outras pessoas em ideias e projetos.',mid:'Costuma se comunicar de forma adaptável, alternando exposição e reserva conforme pessoas e contexto.',low:'Tende a ser mais reservado na exposição, preferindo interações com propósito claro e comunicação menos expansiva.',managerHigh:'Use diálogo, reconhecimento específico e espaço para interação. Observe dispersão, promessas em excesso ou perda de detalhes quando a empolgação cresce.',managerLow:'Não confunda reserva com falta de capacidade. Dê tempo de preparação e canais de comunicação adequados. Observe se ideias importantes ficam retidas por pouca exposição.',personalHigh:'Seu desenvolvimento passa por equilibrar entusiasmo com escuta, consistência, organização e acompanhamento do que foi combinado.',personalLow:'Pode ser útil praticar exposição de ideias, síntese verbal e participação intencional em situações em que sua voz precisa aparecer.'},
 S:{name:'Estabilidade',measures:'Constância, paciência, cooperação, preferência por previsibilidade e ritmo sustentado.',high:'Tende a valorizar estabilidade, relações confiáveis e mudanças bem explicadas. Pode demonstrar paciência e constância.',mid:'Consegue lidar com rotina e mudança de forma relativamente equilibrada, dependendo do nível de segurança e do contexto.',low:'Tende a aceitar mudanças e variação com mais facilidade, podendo preferir ambientes rápidos e menos previsíveis.',managerHigh:'Antecipe mudanças, explique motivos e dê tempo razoável de adaptação. Observe resistência silenciosa, dificuldade de dizer não e manutenção de situações que já precisam mudar.',managerLow:'Ofereça variedade e desafios, mas acompanhe consistência e continuidade. Observe perda de interesse em rotinas longas.',personalHigh:'Seu desenvolvimento pode envolver maior flexibilidade diante de mudanças, comunicação de incômodos e decisão mais rápida quando o contexto exige.',personalLow:'Seu desafio pode ser sustentar processos, criar cadência e não abandonar tarefas importantes quando a novidade diminui.'},
 C:{name:'Conformidade / Critério',measures:'Atenção a detalhes, precisão, padrões, análise, organização e necessidade de critérios claros.',high:'Tende a conferir informações, valorizar qualidade e buscar segurança por meio de dados, padrões e organização.',mid:'Tende a equilibrar precisão e pragmatismo, aprofundando a análise quando percebe maior risco ou complexidade.',low:'Tende a priorizar velocidade e flexibilidade em vez de detalhamento intenso ou regras rígidas.',managerHigh:'Forneça critérios, contexto e padrão de qualidade. Evite mudanças vagas ou instruções contraditórias. Observe perfeccionismo, demora por excesso de análise e rigidez com erros.',managerLow:'Defina controles essenciais e pontos de checagem. Observe descuido com detalhes, documentação e repetibilidade.',personalHigh:'Seu desenvolvimento pode envolver decidir com informação suficiente, não perfeita, além de tolerar variações que não comprometem o resultado.',personalLow:'Pode ser útil criar checklists, rotinas de revisão e critérios mínimos para reduzir erros por pressa ou improviso.'}
};

const valueInfo:any={
 'Religioso / Espiritual':{measures:'Busca de sentido, coerência com convicções, princípios pessoais e percepção de propósito maior.',high:'Tende a se engajar mais quando percebe significado, coerência ética e conexão entre trabalho e princípios.',low:'Propósito e convicções podem ter menor peso relativo na decisão profissional, sem que isso indique ausência de valores ou ética.',manager:'Evite inferir religião, moralidade ou caráter a partir desta pontuação. Use o resultado apenas para compreender quanto sentido e alinhamento com princípios pesam na motivação.',develop:'Reflita sobre quais princípios são inegociáveis para você e como eles orientam decisões, prioridades e limites.'},
 'Teórico':{measures:'Busca por conhecimento, compreensão, lógica, evidências, aprendizado e aprofundamento.',high:'Tende a sentir motivação ao aprender, compreender causas e dominar um assunto antes de concluir.',low:'Pode preferir aplicação prática e experiência direta a longos períodos de estudo ou investigação conceitual.',manager:'Quando alto, ofereça contexto, dados e oportunidade de aprendizado. Quando baixo, seja objetivo e conecte informação à aplicação.',develop:'Observe quando aprofundar aumenta a qualidade e quando a busca por mais informação apenas adia a ação.'},
 'Estético':{measures:'Valorização de beleza, harmonia, criatividade, experiência, expressão e qualidade do ambiente.',high:'Tende a perceber forma, atmosfera, estética e qualidade da experiência como elementos importantes.',low:'Pode priorizar funcionalidade, resultado e praticidade, dando menor peso relativo à forma ou à experiência estética.',manager:'Quando alto, ambientes, apresentação e liberdade criativa podem influenciar engajamento. Quando baixo, conecte escolhas estéticas a objetivos concretos.',develop:'Use sua sensibilidade para elevar qualidade sem deixar que preferência pessoal se transforme em perfeccionismo ou dificuldade de aceitar soluções funcionais.'},
 'Econômico':{measures:'Foco em utilidade, eficiência, produtividade, retorno e transformação de recursos em resultados.',high:'Tende a avaliar escolhas pelo resultado concreto, eficiência e retorno obtido.',low:'Pode dar maior prioridade a propósito, pessoas, conhecimento ou experiência do que ao retorno mensurável imediato.',manager:'Quando alto, deixe metas, indicadores e impacto claros. Quando baixo, ajude a conectar tarefas a resultados sem reduzir toda motivação a números.',develop:'Equilibre eficiência com qualidade, relações e sustentabilidade. Nem tudo que tem valor gera retorno imediato e mensurável.'},
 'Social':{measures:'Motivação por contribuir, apoiar, cooperar e gerar impacto positivo em outras pessoas.',high:'Tende a encontrar satisfação em ajudar, apoiar, orientar e perceber benefício humano no que faz.',low:'Pode separar mais claramente trabalho e cuidado relacional, priorizando outros motivadores.',manager:'Quando alto, mostre impacto nas pessoas e reconheça contribuições coletivas. Observe sobrecarga por dificuldade de estabelecer limites.',develop:'Pratique ajudar sem assumir responsabilidades que pertencem aos outros. Cuidado também envolve limite, clareza e responsabilização.'},
 'Político / Liderança e Influência':{measures:'Busca por protagonismo, influência, liderança, reconhecimento, poder de decisão e capacidade de direcionar grupos.',high:'Tende a sentir energia quando pode influenciar, liderar, assumir visibilidade ou participar de decisões relevantes.',low:'Pode preferir contribuição técnica ou cooperativa sem necessidade constante de protagonismo ou status.',manager:'Quando alto, ofereça responsabilidade real e critérios claros de autoridade. Observe competição, centralização ou busca excessiva por reconhecimento.',develop:'Desenvolva influência baseada em confiança, competência e serviço, não apenas em posição, controle ou visibilidade.'}
};

const workInfo:any={
 Autonomia:{measures:'Preferência por liberdade para decidir como executar objetivos.',high:'Tende a produzir melhor com espaço de decisão e pouca supervisão operacional.',low:'Pode preferir orientação mais próxima, alinhamentos frequentes e limites bem definidos.',manager:'Ajuste o grau de autonomia ao nível de experiência e risco da função. Autonomia não significa ausência de responsabilidade.',develop:'Pratique assumir decisões dentro de limites claros e comunicar riscos antes que virem problemas.'},
 Estrutura:{measures:'Preferência por processos, expectativas, regras e critérios claramente definidos.',high:'Tende a trabalhar melhor quando sabe exatamente o que se espera e quais parâmetros deve seguir.',low:'Pode tolerar melhor ambiguidade, improviso e construção de caminhos durante a execução.',manager:'Quando alto, reduza ambiguidades e mudanças contraditórias. Quando baixo, mantenha apenas os controles indispensáveis.',develop:'Aprenda a distinguir estrutura que protege qualidade de burocracia que apenas consome energia.'},
 Variedade:{measures:'Necessidade de mudança, novidade, novos desafios e diversidade de tarefas.',high:'Tende a ganhar energia com mudanças, projetos diferentes e novos estímulos.',low:'Pode preferir aprofundamento, previsibilidade e continuidade.',manager:'Quando alto, varie desafios sem perder acompanhamento. Quando baixo, introduza mudanças com lógica e tempo de adaptação.',develop:'Se gosta de variedade, desenvolva constância. Se prefere estabilidade, exercite adaptação gradual a novidades.'},
 Concentracao:{measures:'Preferência por períodos de foco com poucas interrupções.',high:'Tende a produzir melhor quando consegue proteger blocos de atenção e finalizar raciocínios.',low:'Pode lidar melhor com interrupções, alternância de demandas e interação frequente.',manager:'Proteja blocos de foco quando a função exigir profundidade. Não interprete necessidade de concentração como isolamento.',develop:'Crie uma rotina que combine disponibilidade para pessoas com períodos claros de atenção profunda.'}
};

function level(v:number){return v>=4?'alto':v>=3?'moderado':v>=2?'moderado-baixo':'baixo'}
function behaviorDetailedRows(r:any,mode:'manager'|'personal'){
 if(!r)return'';
 const discSorted=Object.entries(r.disc||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1]));
 const valuesSorted=Object.entries(r.values||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1]));
 const primary=discSorted[0]?.[0] as string; const secondary=discSorted[1]?.[0] as string;
 const topValues=valuesSorted.slice(0,3).map(([k])=>k);
 const socialScore=Number(r.socialScore||3);
 const integrated=`O perfil apresenta maior expressão em ${discInfo[primary]?.name||primary}${secondary?` com apoio de ${discInfo[secondary]?.name||secondary}`:''}. O estilo social foi classificado como ${r.style||'-'}. Entre os motivadores declarados, destacam-se ${topValues.join(', ')}. Essa combinação deve ser entendida como uma tendência, não como uma identidade fixa: contexto, experiência, cultura e responsabilidade podem alterar a forma como esses traços aparecem.`;
 let html=`<div class="box"><h2>1. Síntese integrada</h2><p>${integrated}</p>${mode==='manager'?`<div class="callout"><b>Uso gerencial:</b> use esta síntese para formular hipóteses e perguntas. Confirme sempre com exemplos reais de comportamento, histórico e exigências da função.</div>`:`<div class="callout"><b>Para seu desenvolvimento:</b> use o relatório para reconhecer padrões, não para se limitar. O objetivo é ampliar repertório e escolha consciente de comportamento.</div>`}</div>`;
 html+=`<div class="box"><h2>2. Perfil comportamental - DISC</h2><p class="small">Escala de 1 a 5. Pontuações maiores indicam maior presença declarada daquela tendência.</p>`;
 for(const [k,v0] of discSorted as any){const v=Number(v0);const i=discInfo[k];const interp=v>=3.7?i.high:v<=2.3?i.low:i.mid;const guidance=mode==='manager'?(v>=3.7?i.managerHigh:v<=2.3?i.managerLow:`Observe como esta dimensão aparece em situações de pressão, mudança, conflito e decisão.`):(v>=3.7?i.personalHigh:v<=2.3?i.personalLow:`Você tende a ter flexibilidade nesta dimensão. Observe em quais contextos ela sobe ou desce.`);html+=`<div class="item"><h3>${i.name} <span class="score">${v.toFixed(1)}/5 - ${level(v)}</span></h3><p><b>O que mede:</b> ${i.measures}</p><p><b>O que seu resultado sugere:</b> ${interp}</p><p><b>${mode==='manager'?'Implicação para gestão':'Ponto de desenvolvimento'}:</b> ${guidance}</p></div>`}
 html+=`</div>`;
 html+=`<div class="box"><h2>3. Estilo social</h2><h3>${r.style||'-'} <span class="score">${socialScore.toFixed(1)}/5</span></h3><p><b>O que mede:</b> preferência por interação, exposição social e forma de processar ideias. Não mede qualidade de comunicação, inteligência social ou capacidade de relacionamento.</p><p><b>Leitura:</b> ${r.style==='Extrovertido'?'Há maior tendência a ganhar energia na interação, iniciar conversas e processar ideias em contato com outras pessoas.':r.style==='Introvertido'?'Há maior tendência a processar internamente, selecionar interações e precisar de períodos de reserva para recuperar energia e organizar ideias.':'Há equilíbrio entre exposição e reserva. A pessoa pode alternar bastante conforme grupo, tema, confiança e contexto.'}</p><p><b>${mode==='manager'?'Implicação para gestão':'Desenvolvimento'}:</b> ${mode==='manager'?(r.style==='Introvertido'?'Não pressione exposição imediata como prova de engajamento. Dê preparação para reuniões e canais escritos quando fizer sentido.':r.style==='Extrovertido'?'Use interação como recurso, mas preserve espaço para escuta, foco e preparação individual.':'A pessoa tende a adaptar o grau de interação; observe qual contexto aumenta ou reduz sua participação.'):(r.style==='Introvertido'?'Desenvolva exposição intencional sem tentar se transformar em alguém expansivo. Preparação e clareza podem aumentar sua presença.':r.style==='Extrovertido'?'Proteja momentos de reflexão e escuta para que a rapidez social não substitua análise e profundidade.':'Use sua capacidade de alternar interação e reserva de forma consciente, conforme a tarefa exigir.')}</p></div>`;
 html+=`<div class="box"><h2>4. Valores e motivadores</h2><p class="small">Estrutura baseada nos seis valores de Spranger, com perguntas autorais. As pontuações representam motivadores declarados e não caráter, religião, ética ou mérito profissional.</p>`;
 for(const [k,v0] of valuesSorted as any){const v=Number(v0);const i=valueInfo[k];const interp=v>=3.7?i.high:v<=2.3?i.low:`Este motivador aparece de forma moderada e tende a ganhar ou perder importância conforme contexto e fase de vida.`;html+=`<div class="item"><h3>${k} <span class="score">${v.toFixed(1)}/5 - ${level(v)}</span></h3><p><b>O que mede:</b> ${i?.measures||''}</p><p><b>O que o resultado sugere:</b> ${interp}</p><p><b>${mode==='manager'?'Implicação para gestão':'Reflexão de desenvolvimento'}:</b> ${mode==='manager'?i?.manager:i?.develop}</p></div>`}
 html+=`<p><b>Três valores mais presentes:</b> ${topValues.join(' + ')}</p></div>`;
 html+=`<div class="box"><h2>5. Preferências de ambiente de trabalho</h2><p class="small">Essas pontuações indicam condições que podem facilitar conforto e desempenho, mas não determinam capacidade.</p>`;
 for(const [k,v0] of Object.entries(r.work||{}) as any){const v=Number(v0);const i=workInfo[k];const interp=v>=3.7?i.high:v<=2.3?i.low:`A preferência é moderada. A pessoa tende a se adaptar, dependendo da tarefa, do risco e da experiência.`;html+=`<div class="item"><h3>${k==='Concentracao'?'Concentração':k} <span class="score">${v.toFixed(1)}/5 - ${level(v)}</span></h3><p><b>O que mede:</b> ${i?.measures||''}</p><p><b>Leitura:</b> ${interp}</p><p><b>${mode==='manager'?'Implicação para gestão':'Ação prática'}:</b> ${mode==='manager'?i?.manager:i?.develop}</p></div>`}
 html+=`</div>`;
 if(mode==='manager'){
  html+=`<div class="box"><h2>6. Perguntas para entrevista ou feedback</h2><ul><li>Em quais situações você costuma decidir rapidamente e em quais prefere analisar mais antes de agir?</li><li>Conte um exemplo de uma mudança que exigiu adaptação. O que facilitou ou dificultou?</li><li>Qual tipo de reconhecimento ou resultado mais aumenta sua motivação?</li><li>Em que tipo de ambiente você sente que produz seu melhor trabalho? O que costuma atrapalhar?</li><li>Qual comportamento seu já precisou ser ajustado para funcionar melhor com uma equipe diferente?</li></ul><div class="callout"><b>Importante:</b> essas perguntas servem para validar o relatório com exemplos concretos. Não trate uma pontuação isolada como evidência suficiente para uma decisão de RH.</div></div>`;
 }else{
  html+=`<div class="box"><h2>6. Plano de desenvolvimento pessoal</h2><p>Escolha no máximo dois comportamentos para desenvolver por ciclo. Mudança sustentável costuma vir de prática observável, não de tentar alterar sua personalidade.</p><ul><li><b>Manter:</b> escolha uma força que já traz bons resultados e defina como continuar usando-a sem exagero.</li><li><b>Desenvolver:</b> escolha uma tendência baixa ou um excesso que hoje limita sua atuação.</li><li><b>Prática semanal:</b> transforme o objetivo em uma ação pequena e repetível.</li><li><b>Evidência:</b> defina como saberá que houve melhora: feedback, prazo, qualidade, autonomia, redução de retrabalho ou outro indicador.</li><li><b>Revisão:</b> após 30 dias, registre o que funcionou, o que não funcionou e qual será o próximo ajuste.</li></ul></div>`;
 }
 return html;
}
function vocRows(r:any){const labels:any={pratico:'Prático',investigativo:'Investigativo',criativo:'Criativo',social:'Social',empreendedor:'Empreendedor',organizacional:'Organizacional'};const sorted=Object.entries(r||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1]));return `<div class="box"><h2>Áreas de interesse</h2><table><tbody>${sorted.map(([k,v])=>`<tr><td>${labels[k]||k}</td><td>${v}/25</td></tr>`).join('')}</tbody></table></div><div class="box"><h2>Interesses predominantes</h2><p>${sorted.slice(0,3).map(([k])=>labels[k]||k).join(' + ')}</p></div>`}
function escapeHtml(s:string){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'} as any)[c])}
