'use client';
import { useEffect,useMemo,useState } from 'react';

type Assessment={id:string,participant_name:string,respondent_name?:string|null,participant_contact:string|null,context:string|null,type:'behavioral'|'vocational',status:string,created_at:string,completed_at:string|null,token:string,result:any,deleted_at?:string|null,deletion_reason?:string|null};
type View='dashboard'|'new'|'behavioral'|'vocational'|'reports'|'deleted';

export default function AdminClient(){
 const [items,setItems]=useState<Assessment[]>([]);
 const [view,setView]=useState<View>('dashboard');
 const [name,setName]=useState(''); const [start,setStart]=useState(''); const [end,setEnd]=useState(''); const [status,setStatus]=useState('');
 const [form,setForm]=useState({participant_name:'',participant_contact:'',context:'',type:'behavioral'});
 const [created,setCreated]=useState<string|null>(null); const [toast,setToast]=useState('');
 const showDeleted=view==='deleted';
 async function load(){const r=await fetch(`/api/assessments${showDeleted?'?deleted=1':''}`,{cache:'no-store'});if(r.ok)setItems(await r.json())}
 useEffect(()=>{load()},[showDeleted]);
 async function create(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/assessments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(r.ok){setCreated(d.url);setForm({participant_name:'',participant_contact:'',context:'',type:'behavioral'});load()}else alert(d.error||'Erro ao criar avaliação')}
 async function copyLink(url:string){try{await navigator.clipboard.writeText(url);setToast('Link copiado');setTimeout(()=>setToast(''),2200)}catch{window.prompt('Copie o link:',url)}}
 async function removeItem(x:Assessment){const reason=window.prompt('Motivo da exclusão (opcional):','Preenchimento incorreto');if(reason===null)return;if(!window.confirm(`Excluir o relatório de ${x.participant_name}? Ele irá para Relatórios excluídos e poderá ser restaurado.`))return;const r=await fetch('/api/assessments',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:x.id,reason})});const d=await r.json();if(!r.ok)return alert(d.error||'Não foi possível excluir.');load()}
 async function restoreItem(x:Assessment){const r=await fetch('/api/assessments',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:x.id,action:'restore'})});const d=await r.json();if(!r.ok)return alert(d.error||'Não foi possível restaurar.');load()}
 async function permanentlyDelete(x:Assessment){if(!window.confirm(`Excluir definitivamente ${x.participant_name}? Esta ação não poderá ser desfeita.`))return;const r=await fetch('/api/assessments',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:x.id,action:'permanent'})});const d=await r.json();if(!r.ok)return alert(d.error||'Não foi possível excluir definitivamente.');load()}
 const filtered=useMemo(()=>items.filter(x=>{const d=new Date(x.completed_at||x.created_at);const q=(x.respondent_name||x.participant_name).toLowerCase().includes(name.toLowerCase())||x.participant_name.toLowerCase().includes(name.toLowerCase());const a=!start||d>=new Date(start+'T00:00:00');const b=!end||d<=new Date(end+'T23:59:59.999');const s=!status||x.status===status;const t=view==='behavioral'?x.type==='behavioral':view==='vocational'?x.type==='vocational':view==='reports'?x.status==='completed':true;return q&&a&&b&&s&&t}),[items,name,start,end,status,view]);
 const done=items.filter(x=>x.status==='completed').length; const pending=items.filter(x=>x.status!=='completed'&&x.status!=='cancelled').length; const month=items.filter(x=>{const d=new Date(x.completed_at||x.created_at),n=new Date();return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear()}).length;
 const statusLabel=(s:string)=>s==='completed'?'Concluído':s==='started'?'Iniciado':s==='cancelled'?'Cancelado':'Pendente';
 const nav=(v:View,label:string,icon:string)=><button className={'side-link '+(view===v?'active':'')} onClick={()=>{setView(v);setCreated(null)}}><span>{icon}</span>{label}</button>;
 return <div className="admin-shell">
  <aside className="sidebar">
   <div className="sidebar-brand"><div className="brand-mark">PV</div><div><b>Perfil & Vocacional</b><small>Gestão de avaliações</small></div></div>
   <nav className="side-nav">{nav('dashboard','Dashboard','⌂')}{nav('new','Nova avaliação','＋')}{nav('behavioral','Perfil comportamental','◫')}{nav('vocational','Teste vocacional','◇')}{nav('reports','Relatórios','▤')}{nav('deleted','Excluídos','⌫')}</nav>
   <div className="sidebar-note"><span className="dot-live"/>Sistema conectado</div>
  </aside>
  <main className="admin-main">
   {toast&&<div className="toast">✓ {toast}</div>}
   <header className="page-head"><div><p className="eyebrow">PAINEL ADMINISTRATIVO</p><h1>{view==='dashboard'?'Dashboard':view==='new'?'Nova avaliação':view==='behavioral'?'Perfil comportamental':view==='vocational'?'Teste vocacional':view==='reports'?'Relatórios':'Relatórios excluídos'}</h1><p className="muted">{view==='dashboard'?'Acompanhe avaliações, respostas e resultados em um só lugar.':view==='new'?'Gere um link individual e de uso único para cada participante.':view==='deleted'?'Restaure ou exclua definitivamente registros removidos.':'Pesquise, filtre e acompanhe as avaliações.'}</p></div>{view!=='new'&&view!=='deleted'&&<button className="btn btn-primary" onClick={()=>setView('new')}>＋ Nova avaliação</button>}</header>
   {view==='dashboard'&&<><section className="kpi-grid"><div className="metric-card"><span>Total de avaliações</span><strong>{items.length}</strong><small>registros ativos</small></div><div className="metric-card"><span>Aguardando resposta</span><strong>{pending}</strong><small>links em aberto</small></div><div className="metric-card"><span>Concluídas</span><strong>{done}</strong><small>resultados disponíveis</small></div><div className="metric-card"><span>Este mês</span><strong>{month}</strong><small>avaliações movimentadas</small></div></section><section className="card"><div className="section-head"><div><p className="eyebrow">RECENTES</p><h2>Últimas avaliações</h2></div><button className="btn btn-ghost" onClick={()=>setView('reports')}>Ver todas</button></div><AssessmentTable rows={items.slice(0,8)} showDeleted={false} statusLabel={statusLabel} copyLink={copyLink} removeItem={removeItem} restoreItem={restoreItem} permanentlyDelete={permanentlyDelete} openReport={openReport}/></section></>}
   {view==='new'&&<section className="card form-card"><div className="section-head"><div><p className="eyebrow">NOVO LINK</p><h2>Criar avaliação</h2><p className="muted">Escolha o tipo de teste e gere um link exclusivo. O participante poderá responder apenas uma vez.</p></div></div><div className="type-cards"><button type="button" className={'type-card '+(form.type==='behavioral'?'selected':'')} onClick={()=>setForm({...form,type:'behavioral'})}><span className="type-icon">◫</span><b>Perfil Comportamental</b><small>DISC, comunicação, valores e ambiente de trabalho</small></button><button type="button" className={'type-card '+(form.type==='vocational'?'selected':'')} onClick={()=>setForm({...form,type:'vocational'})}><span className="type-icon">◇</span><b>Teste Vocacional</b><small>Interesses, habilidades, preferências e valores de carreira</small></button></div><form onSubmit={create} className="grid grid-2 modern-form"><div><label className="label">Nome de referência</label><input className="input" required value={form.participant_name} onChange={e=>setForm({...form,participant_name:e.target.value})} placeholder="Ex.: Maria Silva"/></div><div><label className="label">Contato (opcional)</label><input className="input" value={form.participant_contact} onChange={e=>setForm({...form,participant_contact:e.target.value})} placeholder="E-mail ou WhatsApp"/></div><div className="span-2"><label className="label">Vaga, setor ou objetivo</label><input className="input" value={form.context} onChange={e=>setForm({...form,context:e.target.value})} placeholder="Ex.: Vendedora / Desenvolvimento de liderança"/></div><div className="span-2"><button className="btn btn-primary btn-large">Gerar link individual</button></div></form>{created&&<div className="link-success"><div><small>LINK INDIVIDUAL DE USO ÚNICO</small><div className="generated-link">{created}</div></div><button className="btn btn-copy" onClick={()=>copyLink(created)}>⧉ Copiar link</button></div>}</section>}
   {view!=='dashboard'&&view!=='new'&&<section className="card"><div className="section-head"><div><p className="eyebrow">HISTÓRICO</p><h2>{view==='deleted'?'Relatórios excluídos':view==='behavioral'?'Avaliações comportamentais':view==='vocational'?'Testes vocacionais':'Resultados concluídos'}</h2></div></div><div className="filters"><div className="filter-search"><label className="label">Pesquisar nome</label><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Digite um nome"/></div><div><label className="label">Data inicial</label><input className="input" type="date" value={start} onChange={e=>setStart(e.target.value)}/></div><div><label className="label">Data final</label><input className="input" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div>{view!=='deleted'&&<div><label className="label">Status</label><select className="input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option><option value="pending">Pendente</option><option value="started">Iniciado</option><option value="completed">Concluído</option><option value="cancelled">Cancelado</option></select></div>}<button className="btn btn-ghost filter-clear" onClick={()=>{setName('');setStart('');setEnd('');setStatus('')}}>Limpar filtros</button></div><AssessmentTable rows={filtered} showDeleted={showDeleted} statusLabel={statusLabel} copyLink={copyLink} removeItem={removeItem} restoreItem={restoreItem} permanentlyDelete={permanentlyDelete} openReport={openReport}/></section>}
  </main>
 </div>
 function openReport(x:Assessment,mode:'manager'|'personal'|'vocational'){
  const w=window.open('','_blank');if(!w)return;const result=x.result||{};
  const title=x.type==='vocational'?'Relatório de Orientação Vocacional':mode==='manager'?'Relatório Gerencial de Perfil Comportamental':'Relatório de Desenvolvimento Pessoal';
  const rows=x.type==='behavioral'?behaviorDetailedRows(result,mode==='manager'?'manager':'personal'):vocRows(result);
  w.document.write(`<html><head><meta charset="utf-8"><title>${title} - ${escapeHtml(x.respondent_name||x.participant_name)}</title><style>body{font-family:Arial,sans-serif;padding:38px;color:#263433;line-height:1.55;max-width:900px;margin:auto}h1{color:#174e4a;margin-bottom:6px}h2{color:#174e4a;margin-top:0}h3{color:#314744;margin-bottom:6px}.sub{color:#687b78;margin-top:0}.box{border:1px solid #dce6e3;border-radius:14px;padding:20px;margin:17px 0;page-break-inside:avoid}.item{border-top:1px solid #e9efed;padding-top:14px;margin-top:14px}.item:first-of-type{border-top:0;padding-top:0;margin-top:0}.score{font-weight:700;color:#174e4a}.callout{background:#f4f8f7;border-left:4px solid #6f918b;padding:12px 14px;margin:12px 0}.small{font-size:12px;color:#687b78}.barrow{margin:12px 0}.barlabel{display:flex;justify-content:space-between;gap:12px;font-size:13px}.track{height:12px;background:#e8efed;border-radius:999px;overflow:hidden}.fill{height:100%;background:#174e4a;border-radius:999px}.note{font-size:12px;color:#666;margin-top:30px}ul{margin-top:6px;padding-left:20px}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #eee;padding:8px;text-align:left}@media print{button{display:none}body{padding:10px}.box{break-inside:avoid}}</style></head><body><h1>${title}</h1><p class="sub">Leitura explicada, item a item, dos resultados da avaliação.</p><p><b>Nome:</b> ${escapeHtml(x.respondent_name||x.participant_name)}<br/><b>Contexto:</b> ${escapeHtml(x.context||'-')}<br/><b>Data:</b> ${new Date(x.completed_at||x.created_at).toLocaleDateString('pt-BR')}</p>${rows}<div class="note">Este relatório é uma ferramenta de apoio ao autoconhecimento, desenvolvimento e conversas de gestão. Não constitui diagnóstico psicológico e não deve ser usado isoladamente para decisões de contratação, promoção, desligamento ou carreira. Resultados descrevem tendências declaradas no momento da avaliação e devem ser confrontados com comportamentos observáveis e contexto.</div><br/><button onclick="window.print()">Salvar / Imprimir PDF</button></body></html>`);w.document.close()
 }
}

function AssessmentTable({rows,showDeleted,statusLabel,copyLink,removeItem,restoreItem,permanentlyDelete,openReport}:{rows:Assessment[],showDeleted:boolean,statusLabel:(s:string)=>string,copyLink:(u:string)=>void,removeItem:(x:Assessment)=>void,restoreItem:(x:Assessment)=>void,permanentlyDelete:(x:Assessment)=>void,openReport:(x:Assessment,m:'manager'|'personal'|'vocational')=>void}){
 return <div className="table-wrap"><table className="modern-table"><thead><tr><th>Nome</th><th>Tipo</th><th>Contexto</th><th>Status</th><th>Data</th>{showDeleted&&<th>Motivo</th>}<th>Ações</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><b>{x.respondent_name||x.participant_name}</b></td><td><span className="type-pill">{x.type==='behavioral'?'Comportamental':'Vocacional'}</span></td><td>{x.context||'-'}</td><td><span className={'badge '+(x.status==='completed'?'ok':x.status==='started'?'started':x.status==='cancelled'?'cancelled':'')}>{statusLabel(x.status)}</span></td><td>{new Date(x.completed_at||x.created_at).toLocaleDateString('pt-BR')}</td>{showDeleted&&<td>{x.deletion_reason||'-'}</td>}<td><div className="actions">{showDeleted?<><button className="icon-btn" title="Restaurar" onClick={()=>restoreItem(x)}>↶</button><button className="icon-btn danger" title="Excluir definitivamente" onClick={()=>permanentlyDelete(x)}>⌫</button></>:<>{x.status==='completed'?(x.type==='behavioral'?<><button className="btn btn-small" onClick={()=>openReport(x,'manager')}>Gerencial</button><button className="btn btn-small" onClick={()=>openReport(x,'personal')}>Pessoal</button></>:<button className="btn btn-small" onClick={()=>openReport(x,'vocational')}>Relatório</button>):<button className="btn btn-copy btn-small" onClick={()=>copyLink(`${location.origin}/t/${x.token}`)}>⧉ Copiar link</button>}<button className="icon-btn danger" title="Excluir" onClick={()=>removeItem(x)}>⌫</button></>}</div></td></tr>):<tr><td colSpan={showDeleted?7:6}><div className="empty-state">Nenhuma avaliação encontrada com estes filtros.</div></td></tr>}</tbody></table></div>
}
const discInfo:any={
 D:{name:'Dominancia',measures:'Ritmo de decisao, assertividade, iniciativa e foco em resultado.',high:'Maior tendencia a assumir decisoes, enfrentar desafios e buscar autonomia.',low:'Maior tendencia a cautela, cooperacao e menor necessidade de controlar a situacao.',manager:'Observe como a pessoa equilibra velocidade, escuta e impacto das decisoes.',personal:'Use a objetividade quando ela ajuda, mas desenvolva flexibilidade para ouvir, esperar e ajustar.'},
 I:{name:'Influencia',measures:'Expressividade, persuasao, entusiasmo e facilidade de conexao.',high:'Maior tendencia a envolver pessoas pela comunicacao e pelo relacionamento.',low:'Maior tendencia a comunicacao mais seletiva, reservada e orientada ao conteudo.',manager:'Nao confunda expansividade com competencia. Avalie a qualidade da comunicacao e da escuta.',personal:'Desenvolva equilibrio entre expressar ideias, ouvir e adaptar a mensagem ao interlocutor.'},
 S:{name:'Estabilidade',measures:'Constancia, paciencia, cooperacao e preferencia por previsibilidade.',high:'Maior tendencia a manter ritmo constante, apoiar pessoas e valorizar seguranca nas mudancas.',low:'Maior tolerancia a mudanca rapida, variedade e quebra de rotina.',manager:'Explique mudancas, contexto e expectativas de forma proporcional a necessidade da pessoa.',personal:'Fortalezas de constancia podem ser combinadas com pratica deliberada de adaptacao.'},
 C:{name:'Conformidade',measures:'Criterio, qualidade, organizacao, analise e atencao a padroes.',high:'Maior tendencia a analisar, conferir e buscar consistencia antes de concluir.',low:'Maior tendencia a simplificar, experimentar e agir com menos dependencia de regras.',manager:'Ajuste o nivel de detalhe, controle e autonomia a complexidade real da funcao.',personal:'Busque equilibrio entre qualidade e velocidade para evitar tanto retrabalho quanto excesso de analise.'}
};
const valueInfo:any={
 'Religioso / Espiritual':{measures:'Busca de proposito, coerencia com principios, sentido e conviccoes.',manager:'Trate como motivador declarado e nunca como medida de carater, religiao correta ou criterio automatico de contratacao.',personal:'Observe quais atividades aumentam sua percepcao de sentido e coerencia com seus principios.'},
 'Teorico':{measures:'Conhecimento, compreensao, estudo, investigacao e busca de explicacoes.',manager:'Aprendizado, contexto e desafios intelectuais podem aumentar engajamento.',personal:'Transforme curiosidade em conhecimento aplicado, evitando acumular informacao sem execucao.'},
 'Estetico':{measures:'Harmonia, criatividade, beleza, experiencia e qualidade do ambiente.',manager:'Qualidade visual, experiencia e liberdade criativa podem ser motivadores relevantes.',personal:'Use sensibilidade e criatividade sem deixar que a busca pelo ideal paralise a entrega.'},
 'Economico':{measures:'Utilidade, eficiencia, produtividade, resultado e retorno.',manager:'Metas, indicadores e clareza de resultado tendem a tornar o trabalho mais significativo.',personal:'Use foco em resultado sem reduzir pessoas ou processos apenas ao que e mensuravel.'},
 'Social':{measures:'Contribuicao, cooperacao, apoio e impacto positivo nas pessoas.',manager:'Conexao com pessoas e percepcao de contribuicao podem aumentar motivacao.',personal:'Ajude sem assumir responsabilidades que pertencem a outras pessoas; preserve limites.'},
 'Politico / Lideranca e Influencia':{measures:'Protagonismo, influencia, lideranca, reconhecimento e poder de decisao.',manager:'Responsabilidade, visibilidade e oportunidade de influenciar podem ser motivadores.',personal:'Desenvolva influencia com responsabilidade, escuta e clareza de limites.'}
};
function bar(label:string,value:number){return `<div class="barrow"><div class="barlabel"><span>${label}</span><b>${Math.round(value)}%</b></div><div class="track"><div class="fill" style="width:${Math.max(0,Math.min(100,value))}%"></div></div></div>`}
function behaviorDetailedRows(r:any,mode:'manager'|'personal'){
 if(!r)return'';
 const disc=Object.entries(r.disc||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1]));
 const values=Object.entries(r.values||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1]));
 const primary=String(r.discPrimary||disc[0]?.[0]||''); const secondary=String(r.discSecondary||disc[1]?.[0]||'');
 const topValues=values.slice(0,3).map(([k])=>k);
 let html=`<div class="box"><h2>1. Sintese integrada</h2><p>O resultado mostra maior expressao de <b>${discInfo[primary]?.name||primary}</b>${secondary?` com apoio de <b>${discInfo[secondary]?.name||secondary}</b>`:''}. O estilo de comunicacao foi classificado como <b>${r.communication?.classification||'-'}</b>. Entre os valores mais presentes aparecem <b>${topValues.join(', ')}</b>.</p><div class="callout">${mode==='manager'?'<b>Uso gerencial:</b> trate o resultado como hipotese para orientar entrevista, feedback e desenvolvimento. Confirme sempre com exemplos observaveis.':'<b>Uso pessoal:</b> o objetivo nao e rotular sua personalidade, mas ampliar sua consciencia sobre tendencias e escolhas de comportamento.'}</div></div>`;
 html+=`<div class="box"><h2>2. Perfil Comportamental - DISC</h2><p class="small">Percentuais relativos entre as quatro tendencias. A soma e 100% e mostra a composicao desta avaliacao.</p>${disc.map(([k,v]:any)=>bar(`${k} - ${discInfo[k]?.name||k}`,Number(v))).join('')}`;
 for(const [k,v0] of disc as any){const v=Number(v0),i=discInfo[k];html+=`<div class="item"><h3>${k} - ${i.name} <span class="score">${v.toFixed(1)}%</span></h3><p><b>O que mede:</b> ${i.measures}</p><p><b>Leitura:</b> ${k===primary?i.high:i.low}</p><p><b>${mode==='manager'?'Aplicacao gerencial':'Desenvolvimento'}:</b> ${mode==='manager'?i.manager:i.personal}</p></div>`}
 html+=`</div>`;
 const c=r.communication||{};html+=`<div class="box"><h2>3. Estilo de Comunicacao</h2><h3>${c.classification||'-'}</h3>${bar('Extroversao',Number(c.extroversion||0))}${bar('Introversao',Number(c.introversion||0))}<p><b>O que mede:</b> preferencia por exposicao, interacao e processamento social. Nao mede capacidade de comunicacao, inteligencia ou competencia profissional.</p><p><b>Leitura:</b> ${c.classification==='Extrovertido'?'Ha maior preferencia por troca, expressao e interacao como parte do processamento de ideias.':c.classification==='Introvertido'?'Ha maior preferencia por reflexao interna, interacoes mais seletivas e momentos de reserva.':'Ha equilibrio entre interacao e reserva, com maior variacao conforme contexto, grupo e tema.'}</p><p><b>${mode==='manager'?'Aplicacao gerencial':'Desenvolvimento'}:</b> ${mode==='manager'?'Adapte reunioes, feedbacks e canais de comunicacao sem confundir expansividade com engajamento.':'Observe em quais contextos voce se comunica melhor e pratique conscientemente o estilo complementar quando necessario.'}</p></div>`;
 html+=`<div class="box"><h2>4. Valores e Motivadores</h2><p class="small">Percentuais relativos entre os seis valores. Eles representam prioridades e motivadores declarados, nao carater, etica ou merito profissional.</p>${values.map(([k,v]:any)=>bar(k,Number(v))).join('')}`;
 for(const [k,v0] of values as any){const v=Number(v0),i=valueInfo[k];html+=`<div class="item"><h3>${k} <span class="score">${v.toFixed(1)}%</span></h3><p><b>O que representa:</b> ${i?.measures||''}</p><p><b>${mode==='manager'?'Aplicacao gerencial':'Reflexao de desenvolvimento'}:</b> ${mode==='manager'?i?.manager:i?.personal}</p></div>`}
 html+=`</div>`;
 html+=`<div class="box"><h2>5. Preferencias no Ambiente de Trabalho</h2><p class="small">Cada linha e um continuo. Nao existe lado certo ou errado; o resultado indica preferencia relativa.</p>`;
 for(const x of Object.values(r.work||{}) as any[]){html+=`<div class="item"><h3>${x.labels?.[0]} x ${x.labels?.[1]}</h3>${bar(x.labels?.[0]||'',Number(x.left||0))}${bar(x.labels?.[1]||'',Number(x.right||0))}</div>`}
 html+=`</div>`;
 if(mode==='manager')html+=`<div class="box"><h2>6. Perguntas para aprofundar</h2><ul><li>Conte uma situacao em que precisou decidir sob pressao. Como chegou a decisao?</li><li>Que tipo de ambiente faz voce produzir melhor? O que costuma atrapalhar?</li><li>Como prefere receber uma orientacao dificil ou um feedback corretivo?</li><li>Qual tipo de resultado ou reconhecimento mais aumenta sua motivacao?</li><li>Que comportamento seu ja precisou ser ajustado para trabalhar melhor com pessoas diferentes?</li></ul></div>`;
 else html+=`<div class="box"><h2>6. Plano de desenvolvimento</h2><ul><li><b>Manter:</b> escolha uma tendencia que ja produz bons resultados e defina como usa-la sem excesso.</li><li><b>Desenvolver:</b> escolha um comportamento complementar que aumentaria sua flexibilidade.</li><li><b>Pratica:</b> defina uma acao pequena e observavel para repetir durante 30 dias.</li><li><b>Evidencia:</b> acompanhe por feedback, qualidade, prazo, autonomia ou reducao de retrabalho.</li></ul></div>`;
 return html;
}
const vocInterestInfo:any={
 realista:{label:'Realista / Pratico',letter:'R',desc:'Interesse por execucao concreta, operacao, ferramentas, campo, producao e solucoes praticas.',families:['Engenharias e areas tecnicas','Logistica, operacoes e manutencao','Arquitetura, construcao e producao','Agronegocio e atividades de campo'],courses:['Engenharias','Cursos tecnicos industriais','Logistica','Arquitetura e Urbanismo','Agronomia']},
 investigativo:{label:'Investigativo',letter:'I',desc:'Interesse por analise, pesquisa, diagnostico, ciencia, dados, tecnologia e resolucao de problemas complexos.',families:['Tecnologia e dados','Pesquisa e ciencias','Saude diagnostica e investigativa','Analise economica e quantitativa'],courses:['Ciencia da Computacao','Ciencia de Dados','Biomedicina','Farmacia','Estatistica','Economia']},
 artistico:{label:'Artistico / Criativo',letter:'A',desc:'Interesse por criacao, expressao, comunicacao, design, linguagem, estetica e novas possibilidades.',families:['Comunicacao e marketing','Design e experiencia','Artes e producao cultural','Conteudo e industrias criativas'],courses:['Publicidade e Propaganda','Design','Marketing','Jornalismo','Arquitetura e Urbanismo','Artes Visuais']},
 social:{label:'Social',letter:'S',desc:'Interesse por ensinar, orientar, cuidar, desenvolver pessoas e gerar impacto humano direto.',families:['Educacao e desenvolvimento','Psicologia e comportamento humano','Recursos Humanos','Saude e cuidado','Projetos sociais'],courses:['Psicologia','Pedagogia','Recursos Humanos','Enfermagem','Servico Social','Fisioterapia']},
 empreendedor:{label:'Empreendedor',letter:'E',desc:'Interesse por lideranca, negociacao, vendas, influencia, gestao, oportunidades e tomada de decisao.',families:['Administracao e gestao','Comercial e vendas','Empreendedorismo e negocios','Direito e negociacao','Gestao de projetos'],courses:['Administracao','Gestao Comercial','Marketing','Direito','Economia','Gestao de Projetos']},
 convencional:{label:'Convencional / Organizacional',letter:'C',desc:'Interesse por organizacao, controles, processos, dados estruturados, planejamento e precisao.',families:['Administracao e operacoes','Financas e controladoria','Contabilidade','Planejamento e processos','Compliance e qualidade'],courses:['Administracao','Ciencias Contabeis','Gestao Financeira','Processos Gerenciais','Logistica','Economia']}
};
const vocSkillLabels:any={practical:'Pratica / execucao',analytical:'Analise e raciocinio',creative:'Criatividade',interpersonal:'Relacionamento e escuta',influence:'Influencia e lideranca',organization:'Organizacao e controle'};
const vocValueLabels:any={stability:'Estabilidade',income:'Remuneracao',purpose:'Proposito',recognition:'Reconhecimento',autonomy:'Autonomia',creativity:'Criatividade',learning:'Aprendizado',leadership:'Lideranca',balance:'Equilibrio de vida',impact:'Impacto social'};
const interestSkillMap:any={realista:'practical',investigativo:'analytical',artistico:'creative',social:'interpersonal',empreendedor:'influence',convencional:'organization'};
function vocRows(r:any){
 if(!r?.interests){const legacyLabels:any={pratico:'Pratico',investigativo:'Investigativo',criativo:'Criativo',social:'Social',empreendedor:'Empreendedor',organizacional:'Organizacional'};const legacy=Object.entries(r||{}).filter(([,v])=>typeof v==='number').sort((a:any,b:any)=>Number(b[1])-Number(a[1]));return `<div class="box"><h2>Resultado de versao anterior</h2><p>Esta avaliacao foi respondida antes da ampliacao do teste vocacional. O resultado original foi preservado.</p><table><tbody>${legacy.map(([k,v])=>`<tr><td>${legacyLabels[k]||k}</td><td>${v}/25</td></tr>`).join('')}</tbody></table></div>`;}
 const interests=Object.entries(r?.interests||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1]));
 const top=(r?.topInterests?.length?r.topInterests:interests.slice(0,3).map(([k])=>k)) as string[];
 const code=r?.riasecCode||top.map(k=>vocInterestInfo[k]?.letter||'').join('');
 const skills=Object.entries(r?.skills||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1]));
 const careerValues=Object.entries(r?.careerValues||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1]));
 const topFamilies=[...new Set(top.flatMap(k=>vocInterestInfo[k]?.families||[]))].slice(0,10);
 const topCourses=[...new Set(top.flatMap(k=>vocInterestInfo[k]?.courses||[]))].slice(0,12);
 let html=`<div class="box"><h2>1. Resumo do perfil vocacional</h2><p>Seu codigo de interesses predominantes e <b>${code||'-'}</b>, formado por ${top.map(k=>`<b>${vocInterestInfo[k]?.label||k}</b>`).join(' + ')}.</p><p>Esse codigo nao determina uma profissao. Ele organiza os tipos de atividade que mais despertaram interesse nesta avaliacao e serve como ponto de partida para explorar cursos, ocupacoes e ambientes profissionais.</p><div class="callout"><b>Leitura importante:</b> interesse, habilidade percebida e valor de carreira sao dimensoes diferentes. Uma boa escolha costuma considerar o encontro entre as tres, alem de realidade de mercado, formacao necessaria e experiencias concretas.</div></div>`;
 html+=`<div class="box"><h2>2. Mapa de interesses - RIASEC</h2><p class="small">As porcentagens indicam intensidade de interesse declarada em cada grupo, de 0% a 100%.</p>${interests.map(([k,v]:any)=>bar(vocInterestInfo[k]?.label||k,Number(v))).join('')}`;
 for(const [k,v0] of interests as any){const i=vocInterestInfo[k];html+=`<div class="item"><h3>${i?.label||k} <span class="score">${Number(v0).toFixed(0)}%</span></h3><p>${i?.desc||''}</p>${top.includes(k)?'<p><b>Entre seus interesses predominantes.</b></p>':''}</div>`}
 html+=`</div>`;
 html+=`<div class="box"><h2>3. Preferencias de trabalho</h2><p class="small">Cada linha representa um continuo. O objetivo e mostrar em que tipo de ambiente voce tende a se sentir mais confortavel, sem indicar certo ou errado.</p>`;
 for(const x of Object.values(r?.preferences||{}) as any[]){html+=`<div class="item"><h3>${x.labels?.[0]} x ${x.labels?.[1]}</h3>${bar(x.labels?.[0]||'',Number(x.left||0))}${bar(x.labels?.[1]||'',Number(x.right||0))}</div>`}
 html+=`</div>`;
 html+=`<div class="box"><h2>4. Habilidades percebidas</h2><p class="small">Mostra onde voce percebe maior facilidade hoje. Nao substitui avaliacao de competencia, desempenho ou experiencia pratica.</p>${skills.map(([k,v]:any)=>bar(vocSkillLabels[k]||k,Number(v))).join('')}</div>`;
 html+=`<div class="box"><h2>5. Valores de carreira</h2><p class="small">O que tende a pesar mais na sua satisfacao profissional. Como cada valor foi avaliado individualmente, use o resultado como ponto de reflexao, nao como ranking definitivo.</p>${careerValues.map(([k,v]:any)=>bar(vocValueLabels[k]||k,Number(v))).join('')}<p><b>Valores mais destacados:</b> ${careerValues.slice(0,4).map(([k])=>vocValueLabels[k]||k).join(', ')}.</p></div>`;
 html+=`<div class="box"><h2>6. Cruzamento entre interesse e habilidade percebida</h2><table><thead><tr><th>Area</th><th>Interesse</th><th>Habilidade relacionada</th><th>Leitura</th></tr></thead><tbody>${top.map(k=>{const sk=interestSkillMap[k];const iv=Number((r?.interests||{})[k]||0),sv=Number((r?.skills||{})[sk]||0);const reading=iv>=65&&sv>=65?'Interesse e facilidade percebida aparecem juntos. Vale explorar com profundidade.':iv>=65&&sv<65?'Ha interesse relevante, mas a habilidade pode precisar de pratica e desenvolvimento.':iv<65&&sv>=65?'Existe facilidade percebida, embora o interesse nao esteja entre os mais altos.':'Area para explorar sem conclusoes precipitadas.';return `<tr><td>${vocInterestInfo[k]?.label||k}</td><td>${iv}%</td><td>${vocSkillLabels[sk]||sk}: ${sv}%</td><td>${reading}</td></tr>`}).join('')}</tbody></table></div>`;
 html+=`<div class="box"><h2>7. Familias profissionais para investigar</h2><p>Com base nos interesses predominantes, estas familias merecem pesquisa. Elas nao representam indicacao automatica de carreira.</p><ul>${topFamilies.map(x=>`<li>${x}</li>`).join('')}</ul></div>`;
 html+=`<div class="box"><h2>8. Cursos e formacoes para explorar</h2><p>Algumas formacoes relacionadas aos grupos de interesse mais altos:</p><ul>${topCourses.map(x=>`<li>${x}</li>`).join('')}</ul><p class="small">Antes de decidir, pesquise grade curricular, rotina real da profissao, possibilidades de atuacao, exigencias de formacao e mercado na regiao em que pretende trabalhar.</p></div>`;
 const prefs=Object.values(r?.preferences||{}) as any[];
 const strongPrefs=prefs.map(x=>Number(x.left||0)>=60?x.labels?.[0]:Number(x.right||0)>=60?x.labels?.[1]:'equilibrio').filter(x=>x&&x!=='equilibrio');
 html+=`<div class="box"><h2>9. Ambiente profissional que pode favorecer voce</h2><p>As suas respostas sugerem maior preferencia por: <b>${strongPrefs.length?strongPrefs.join(', '):'ambientes com equilibrio entre diferentes formas de trabalho'}</b>.</p><p>Use isso para investigar a rotina concreta das profissoes. Duas pessoas na mesma carreira podem trabalhar em ambientes muito diferentes.</p></div>`;
 html+=`<div class="box"><h2>10. Perguntas de reflexao</h2><ul><li>Quais dessas areas eu gostaria de experimentar na pratica antes de escolher?</li><li>Quais atividades me fazem perder a nocao do tempo de forma positiva?</li><li>Em quais materias, projetos ou trabalhos eu ja tive satisfacao real?</li><li>O que pesa mais para mim: interesse pelo tema, rotina de trabalho, remuneracao, estabilidade ou impacto?</li><li>Que habilidade eu estaria disposto a desenvolver por alguns anos?</li><li>Quais profissionais dessas areas eu poderia entrevistar para conhecer a rotina real?</li></ul></div>`;
 html+=`<div class="box"><h2>11. Proximos passos</h2><ol><li>Escolha de 3 a 5 familias profissionais deste relatorio.</li><li>Pesquise pelo menos dois cursos ou ocupacoes dentro de cada familia.</li><li>Converse com profissionais que atuam nessas areas.</li><li>Busque experiencias curtas: cursos introdutorios, visitas, projetos, voluntariado ou atividades praticas.</li><li>Depois das experiencias, reveja o que aumentou ou diminuiu seu interesse.</li></ol></div>`;
 return html;
}
function escapeHtml(s:string){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'} as any)[c])}
