'use client';
import { useEffect,useMemo,useState } from 'react';

type Assessment={id:string,participant_name:string,respondent_name?:string|null,participant_contact:string|null,context:string|null,type:'behavioral'|'vocational',status:string,created_at:string,completed_at:string|null,token:string,result:any,deleted_at?:string|null,deletion_reason?:string|null};
type View='dashboard'|'new'|'behavioral'|'vocational'|'reports'|'deleted';

export default function AdminClient(){
 const [items,setItems]=useState<Assessment[]>([]);
 const [view,setView]=useState<View>('dashboard');
 const [name,setName]=useState(''); const [start,setStart]=useState(''); const [end,setEnd]=useState(''); const [status,setStatus]=useState('');
 const [form,setForm]=useState({participant_name:'',participant_contact:'',context:'',type:'behavioral'});
 const [created,setCreated]=useState<string|null>(null); const [toast,setToast]=useState('');
 const showDeleted=view==='deleted';
 async function load(){const r=await fetch(`/api/assessments${showDeleted?'?deleted=1':''}`,{cache:'no-store'});if(r.ok)setItems(await r.json())}
 useEffect(()=>{load()},[showDeleted]);
 async function create(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/assessments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(r.ok){setCreated(d.url);setForm({participant_name:'',participant_contact:'',context:'',type:'behavioral'});load()}else alert(d.error||'Erro ao criar avaliação')}
 async function copyLink(url:string){try{await navigator.clipboard.writeText(url);setToast('Link copiado');setTimeout(()=>setToast(''),2200)}catch{window.prompt('Copie o link:',url)}}
 async function removeItem(x:Assessment){const reason=window.prompt('Motivo da exclusão (opcional):','Preenchimento incorreto');if(reason===null)return;if(!window.confirm(`Excluir o relatório de ${x.participant_name}? Ele irá para Relatórios excluídos e poderá ser restaurado.`))return;const r=await fetch('/api/assessments',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:x.id,reason})});const d=await r.json();if(!r.ok)return alert(d.error||'Não foi possível excluir.');load()}
 async function restoreItem(x:Assessment){const r=await fetch('/api/assessments',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:x.id,action:'restore'})});const d=await r.json();if(!r.ok)return alert(d.error||'Não foi possível restaurar.');load()}
 async function permanentlyDelete(x:Assessment){if(!window.confirm(`Excluir definitivamente ${x.participant_name}? Esta ação não poderá ser desfeita.`))return;const r=await fetch('/api/assessments',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:x.id,action:'permanent'})});const d=await r.json();if(!r.ok)return alert(d.error||'Não foi possível excluir definitivamente.');load()}
 const filtered=useMemo(()=>items.filter(x=>{const d=new Date(x.completed_at||x.created_at);const q=(x.respondent_name||x.participant_name).toLowerCase().includes(name.toLowerCase())||x.participant_name.toLowerCase().includes(name.toLowerCase());const a=!start||d>=new Date(start+'T00:00:00');const b=!end||d<=new Date(end+'T23:59:59.999');const s=!status||x.status===status;const t=view==='behavioral'?x.type==='behavioral':view==='vocational'?x.type==='vocational':view==='reports'?x.status==='completed':true;return q&&a&&b&&s&&t}),[items,name,start,end,status,view]);
 const done=items.filter(x=>x.status==='completed').length; const pending=items.filter(x=>x.status!=='completed'&&x.status!=='cancelled').length; const month=items.filter(x=>{const d=new Date(x.completed_at||x.created_at),n=new Date();return d.getMonth()===n.getMonth()&&d.getFullYear()===n.getFullYear()}).length;
 const statusLabel=(s:string)=>s==='completed'?'Concluído':s==='started'?'Iniciado':s==='cancelled'?'Cancelado':'Pendente';
 const nav=(v:View,label:string,icon:string)=><button className={'side-link '+(view===v?'active':'')} onClick={()=>{setView(v);setCreated(null)}}><span>{icon}</span>{label}</button>;
 return <div className="admin-shell">
  <aside className="sidebar">
   <div className="sidebar-brand"><div className="brand-mark">PV</div><div><b>Perfil & Vocacional</b><small>Gestão de avaliações</small></div></div>
   <nav className="side-nav">{nav('dashboard','Dashboard','⌂')}{nav('new','Nova avaliação','＋')}{nav('behavioral','Perfil comportamental','◫')}{nav('vocational','Teste vocacional','◇')}<a className="side-link" href="/admin/life-wheel"><span>◉</span>Roda da Vida</a>{nav('reports','Relatórios','▤')}{nav('deleted','Excluídos','⌫')}</nav>
   <div className="sidebar-note"><span className="dot-live"/>Sistema conectado</div>
  </aside>
  <main className="admin-main">
   {toast&&<div className="toast">✓ {toast}</div>}
   <header className="page-head"><div><p className="eyebrow">PAINEL ADMINISTRATIVO</p><h1>{view==='dashboard'?'Dashboard':view==='new'?'Nova avaliação':view==='behavioral'?'Perfil comportamental':view==='vocational'?'Teste vocacional':view==='reports'?'Relatórios':'Relatórios excluídos'}</h1><p className="muted">{view==='dashboard'?'Acompanhe avaliações, respostas e resultados em um só lugar.':view==='new'?'Gere um link individual e de uso único para cada participante.':view==='deleted'?'Restaure ou exclua definitivamente registros removidos.':'Pesquise, filtre e acompanhe as avaliações.'}</p></div>{view!=='new'&&view!=='deleted'&&<button className="btn btn-primary" onClick={()=>setView('new')}>＋ Nova avaliação</button>}</header>
   {view==='dashboard'&&<><section className="kpi-grid"><div className="metric-card"><span>Total de avaliações</span><strong>{items.length}</strong><small>registros ativos</small></div><div className="metric-card"><span>Aguardando resposta</span><strong>{pending}</strong><small>links em aberto</small></div><div className="metric-card"><span>Concluídas</span><strong>{done}</strong><small>resultados disponíveis</small></div><div className="metric-card"><span>Este mês</span><strong>{month}</strong><small>avaliações movimentadas</small></div></section><section className="card"><div className="section-head"><div><p className="eyebrow">RECENTES</p><h2>Últimas avaliações</h2></div><button className="btn btn-ghost" onClick={()=>setView('reports')}>Ver todas</button></div><AssessmentTable rows={items.slice(0,8)} showDeleted={false} statusLabel={statusLabel} copyLink={copyLink} removeItem={removeItem} restoreItem={restoreItem} permanentlyDelete={permanentlyDelete} openReport={openReport}/></section></>}
   {view==='new'&&<section className="card form-card"><div className="section-head"><div><p className="eyebrow">NOVO LINK</p><h2>Criar avaliação</h2><p className="muted">Escolha o tipo de teste e gere um link exclusivo. O participante poderá responder apenas uma vez.</p></div></div><div className="type-cards"><button type="button" className={'type-card '+(form.type==='behavioral'?'selected':'')} onClick={()=>setForm({...form,type:'behavioral'})}><span className="type-icon">◫</span><b>Perfil Comportamental</b><small>DISC, comunicação, valores e ambiente de trabalho</small></button><button type="button" className={'type-card '+(form.type==='vocational'?'selected':'')} onClick={()=>setForm({...form,type:'vocational'})}><span className="type-icon">◇</span><b>Teste Vocacional</b><small>Interesses, habilidades, preferências e valores de carreira</small></button></div><form onSubmit={create} className="grid grid-2 modern-form"><div><label className="label">Nome de referência</label><input className="input" required value={form.participant_name} onChange={e=>setForm({...form,participant_name:e.target.value})} placeholder="Ex.: Maria Silva"/></div><div><label className="label">Contato (opcional)</label><input className="input" value={form.participant_contact} onChange={e=>setForm({...form,participant_contact:e.target.value})} placeholder="E-mail ou WhatsApp"/></div><div className="span-2"><label className="label">Vaga, setor ou objetivo</label><input className="input" value={form.context} onChange={e=>setForm({...form,context:e.target.value})} placeholder="Ex.: Vendedora / Desenvolvimento de liderança"/></div><div className="span-2"><button className="btn btn-primary btn-large">Gerar link individual</button></div></form>{created&&<div className="link-success"><div><small>LINK INDIVIDUAL DE USO ÚNICO</small><div className="generated-link">{created}</div></div><button className="btn btn-copy" onClick={()=>copyLink(created)}>⧉ Copiar link</button></div>}</section>}
   {view!=='dashboard'&&view!=='new'&&<section className="card"><div className="section-head"><div><p className="eyebrow">HISTÓRICO</p><h2>{view==='deleted'?'Relatórios excluídos':view==='behavioral'?'Avaliações comportamentais':view==='vocational'?'Testes vocacionais':'Resultados concluídos'}</h2></div></div><div className="filters"><div className="filter-search"><label className="label">Pesquisar nome</label><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Digite um nome"/></div><div><label className="label">Data inicial</label><input className="input" type="date" value={start} onChange={e=>setStart(e.target.value)}/></div><div><label className="label">Data final</label><input className="input" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div>{view!=='deleted'&&<div><label className="label">Status</label><select className="input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option><option value="pending">Pendente</option><option value="started">Iniciado</option><option value="completed">Concluído</option><option value="cancelled">Cancelado</option></select></div>}<button className="btn btn-ghost filter-clear" onClick={()=>{setName('');setStart('');setEnd('');setStatus('')}}>Limpar filtros</button></div><AssessmentTable rows={filtered} showDeleted={showDeleted} statusLabel={statusLabel} copyLink={copyLink} removeItem={removeItem} restoreItem={restoreItem} permanentlyDelete={permanentlyDelete} openReport={openReport}/></section>}
  </main>
 </div>
 function openReport(x:Assessment,mode:'summary'|'manager'|'personal'|'vocational'){
  const w=window.open('','_blank');if(!w)return;const result=x.result||{};
  const person=x.respondent_name||x.participant_name;
  const title=x.type==='vocational'?'Relatório de Orientação Vocacional':mode==='summary'?'Relatório Resumido – Perfil Comportamental':mode==='manager'?'Relatório Gerencial de Perfil Comportamental':'Relatório de Desenvolvimento Pessoal';
  const rows=x.type==='behavioral'?(mode==='summary'?behaviorSummaryRows(result,person):behaviorDetailedRows(result,mode==='manager'?'manager':'personal')):vocRows(result);
  const coverGraphic=x.type==='behavioral'?discOverview(result):vocCoverGraphic(result);
  const reportType=x.type==='behavioral'?'Perfil Comportamental':'Orientação Vocacional';
  w.document.write(`<html><head><meta charset="utf-8"><title>${title} - ${escapeHtml(person)}</title><style>
  :root{--ink:#263433;--muted:#6b7c78;--brand:#174e4a;--brand2:#6f918b;--line:#dfe8e5;--soft:#f5f8f7;--d:#d94a45;--i:#f2c94c;--s:#4caf73;--c:#4a7bd0}
  *{box-sizing:border-box;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important;color-adjust:exact!important}html,body{-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important;color-adjust:exact!important}body{margin:0;background:#edf2f0;color:var(--ink);font-family:Inter,Arial,sans-serif;line-height:1.48}.report{max-width:940px;margin:28px auto}.report-cover,.box{background:#fff;border:1px solid var(--line);border-radius:22px;padding:42px 46px;margin:0 0 24px;box-shadow:0 14px 38px rgba(31,68,62,.08)}
  .report-cover{min-height:760px;display:flex;flex-direction:column;justify-content:space-between;background:linear-gradient(145deg,#ffffff 0%,#f5f9f7 72%,#edf4f1 100%);position:relative;overflow:hidden}.report-cover:after{content:'';position:absolute;width:290px;height:290px;border-radius:50%;background:rgba(23,78,74,.055);right:-95px;top:-90px}.cover-kicker,.page-kicker{font-size:11px;letter-spacing:.16em;font-weight:900;color:var(--brand2);text-transform:uppercase}.report-cover h1{font-size:38px;line-height:1.08;color:var(--brand);margin:14px 0 12px;letter-spacing:-.025em}.cover-name{font-size:23px;font-weight:850;margin:4px 0 8px}.cover-meta{display:flex;gap:12px;flex-wrap:wrap;margin-top:14px}.meta-pill{padding:8px 12px;border:1px solid var(--line);background:#fff;border-radius:999px;font-size:12px;color:#536662}.cover-bottom{position:relative;z-index:2}.cover-note{font-size:12px;color:var(--muted);max-width:650px;margin-top:20px}
  .box{position:relative}.box h2{font-size:25px;color:var(--brand);margin:4px 0 16px;letter-spacing:-.015em}.box h3{color:#304642;margin:12px 0 6px;font-size:16px}.sub{color:var(--muted);margin-top:0}.item{border-top:1px solid #e9efed;padding-top:13px;margin-top:13px}.item:first-of-type{border-top:0}.score{font-weight:850;color:var(--brand)}.callout{background:#f2f7f5;border-left:4px solid var(--brand2);padding:13px 15px;margin:14px 0;border-radius:0 12px 12px 0}.small{font-size:12px;color:var(--muted)}.note{font-size:11px;color:#6c7775;margin:24px 2px 0}.barrow{margin:12px 0}.barlabel{display:flex;justify-content:space-between;gap:12px;font-size:13px;margin-bottom:5px}.barlabel b{font-size:12px}.track{height:13px;background:#e9efed;border-radius:999px;overflow:hidden}.fill{height:100%;background:var(--brand);border-radius:999px}.disc-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:18px 0}.disc-card{border-radius:16px;padding:14px 13px;color:#fff;min-height:98px;display:flex;flex-direction:column;justify-content:space-between}.disc-card.i{color:#493b00}.disc-card .letter{font-size:26px;font-weight:950;line-height:1}.disc-card .disc-name{font-size:11px;font-weight:800;opacity:.92}.disc-card .disc-pct{font-size:22px;font-weight:900}.composition{height:15px;border-radius:999px;overflow:hidden;display:flex;background:#eef2f1;margin:8px 0 16px}.composition span{height:100%}.legend{display:flex;flex-wrap:wrap;gap:10px 14px;margin:10px 0 2px;font-size:11px;color:#52635f}.legend i{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:5px}.chart-title{font-size:12px;font-weight:850;color:#52635f;margin:18px 0 8px;text-transform:uppercase;letter-spacing:.06em}.two-col{display:grid;grid-template-columns:1fr 1fr;gap:18px}.mini-stat{border:1px solid var(--line);background:#fafcfc;border-radius:14px;padding:13px}.mini-stat b{display:block;font-size:20px;color:var(--brand)}.tag-list{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.tag{background:#f0f5f3;border:1px solid var(--line);padding:7px 10px;border-radius:999px;font-size:12px;font-weight:700;color:#425753}table{width:100%;border-collapse:collapse;font-size:12px}td,th{border-bottom:1px solid #e8edeb;padding:9px 7px;text-align:left;vertical-align:top}th{color:#536662;background:#f7f9f8}ul,ol{padding-left:20px;margin-top:8px}.report-actions{position:fixed;right:22px;bottom:22px;display:flex;gap:10px;align-items:center;z-index:50}.report-action{border:0;padding:12px 17px;border-radius:12px;font-weight:800;cursor:pointer;box-shadow:0 10px 24px rgba(23,78,74,.20);font-family:inherit}.report-action.pdf{background:var(--brand);color:#fff}.report-action.print{background:#fff;color:var(--brand);border:1px solid var(--line)}
  @media(max-width:700px){.report{margin:0}.report-cover,.box{border-radius:0;border-left:0;border-right:0;padding:28px 20px;margin-bottom:12px}.report-cover{min-height:auto}.report-cover h1{font-size:31px}.disc-grid,.two-col{grid-template-columns:1fr 1fr}.report-actions{right:12px;bottom:12px;flex-direction:column;align-items:stretch}.report-action{padding:10px 13px}}
  @page{size:A4 portrait;margin:0}
  @media print{html,body,*{-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important;color-adjust:exact!important}body{background:#fff}.report{max-width:none;margin:0}.report-cover,.box{width:210mm;min-height:297mm;margin:0;border:0;border-radius:0;box-shadow:none;padding:18mm 17mm;break-after:page;page-break-after:always}.report-cover{display:flex;overflow:hidden}.box{overflow:visible}.box:last-of-type{break-after:auto;page-break-after:auto}.report-actions{display:none!important}.note{font-size:9.5px}.disc-grid{gap:7px}.disc-card{min-height:82px}.item{break-inside:avoid}.barrow{break-inside:avoid}h2,h3{break-after:avoid}}
  </style></head><body><div class="report"><section class="report-cover"><div><div class="cover-kicker">${escapeHtml(reportType)}</div><h1>${escapeHtml(title)}</h1><div class="cover-name">${escapeHtml(person)}</div><div class="cover-meta"><span class="meta-pill">${escapeHtml(x.context||'Sem contexto informado')}</span><span class="meta-pill">${new Date(x.completed_at||x.created_at).toLocaleDateString('pt-BR')}</span></div></div><div class="cover-bottom">${coverGraphic}<p class="cover-note">Leitura visual e interpretativa dos resultados da avaliação. Use este relatório como apoio a conversas de desenvolvimento, gestão e orientação, sempre em conjunto com contexto e comportamentos observáveis.</p></div></section>${rows}<div class="note">Este relatório é uma ferramenta de apoio ao autoconhecimento, desenvolvimento e conversas de gestão. Não constitui diagnóstico psicológico e não deve ser usado isoladamente para decisões de contratação, promoção, desligamento ou carreira. Resultados descrevem tendências declaradas no momento da avaliação e devem ser confrontados com comportamentos observáveis e contexto.</div></div><div class="report-actions"><button class="report-action pdf" onclick="savePdf()">Salvar em PDF</button><button class="report-action print" onclick="window.print()">Imprimir</button></div><script>function savePdf(){window.print()}<\/script></body></html>`);w.document.close()
 }
}

function AssessmentTable({rows,showDeleted,statusLabel,copyLink,removeItem,restoreItem,permanentlyDelete,openReport}:{rows:Assessment[],showDeleted:boolean,statusLabel:(s:string)=>string,copyLink:(u:string)=>void,removeItem:(x:Assessment)=>void,restoreItem:(x:Assessment)=>void,permanentlyDelete:(x:Assessment)=>void,openReport:(x:Assessment,m:'summary'|'manager'|'personal'|'vocational')=>void}){
 return <div className="table-wrap"><table className="modern-table"><thead><tr><th>Nome</th><th>Tipo</th><th>Contexto</th><th>Status</th><th>Data</th>{showDeleted&&<th>Motivo</th>}<th>Ações</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><b>{x.respondent_name||x.participant_name}</b></td><td><span className="type-pill">{x.type==='behavioral'?'Comportamental':'Vocacional'}</span></td><td>{x.context||'-'}</td><td><span className={'badge '+(x.status==='completed'?'ok':x.status==='started'?'started':x.status==='cancelled'?'cancelled':'')}>{statusLabel(x.status)}</span></td><td>{new Date(x.completed_at||x.created_at).toLocaleDateString('pt-BR')}</td>{showDeleted&&<td>{x.deletion_reason||'-'}</td>}<td><div className="actions">{showDeleted?<><button className="icon-btn" title="Restaurar" onClick={()=>restoreItem(x)}>↶</button><button className="icon-btn danger" title="Excluir definitivamente" onClick={()=>permanentlyDelete(x)}>⌫</button></>:<>{x.status==='completed'?(x.type==='behavioral'?<><button className="btn btn-small" onClick={()=>openReport(x,'summary')}>Resumo</button><button className="btn btn-small" onClick={()=>openReport(x,'manager')}>Gerencial</button><button className="btn btn-small" onClick={()=>openReport(x,'personal')}>Pessoal</button></>:<button className="btn btn-small" onClick={()=>openReport(x,'vocational')}>Relatório</button>):<button className="btn btn-copy btn-small" onClick={()=>copyLink(`${location.origin}/t/${x.token}`)}>⧉ Copiar link</button>}<button className="icon-btn danger" title="Excluir" onClick={()=>removeItem(x)}>⌫</button></>}</div></td></tr>):<tr><td colSpan={showDeleted?7:6}><div className="empty-state">Nenhuma avaliação encontrada com estes filtros.</div></td></tr>}</tbody></table></div>
}
const discInfo:any={
 D:{name:'Dominancia',measures:'Ritmo de decisao, assertividade, iniciativa e foco em resultado.',high:'Maior tendencia a assumir decisoes, enfrentar desafios e buscar autonomia.',low:'Maior tendencia a cautela, cooperacao e menor necessidade de controlar a situacao.',manager:'Observe como a pessoa equilibra velocidade, escuta e impacto das decisoes.',personal:'Use a objetividade quando ela ajuda, mas desenvolva flexibilidade para ouvir, esperar e ajustar.'},
 I:{name:'Influencia',measures:'Expressividade, persuasao, entusiasmo e facilidade de conexao.',high:'Maior tendencia a envolver pessoas pela comunicacao e pelo relacionamento.',low:'Maior tendencia a comunicacao mais seletiva, reservada e orientada ao conteudo.',manager:'Nao confunda expansividade com competencia. Avalie a qualidade da comunicacao e da escuta.',personal:'Desenvolva equilibrio entre expressar ideias, ouvir e adaptar a mensagem ao interlocutor.'},
 S:{name:'Estabilidade',measures:'Constancia, paciencia, cooperacao e preferencia por previsibilidade.',high:'Maior tendencia a manter ritmo constante, apoiar pessoas e valorizar seguranca nas mudancas.',low:'Maior tolerancia a mudanca rapida, variedade e quebra de rotina.',manager:'Explique mudancas, contexto e expectativas de forma proporcional a necessidade da pessoa.',personal:'Fortalezas de constancia podem ser combinadas com pratica deliberada de adaptacao.'},
 C:{name:'Conformidade',measures:'Criterio, qualidade, organizacao, analise e atencao a padroes.',high:'Maior tendencia a analisar, conferir e buscar consistencia antes de concluir.',low:'Maior tendencia a simplificar, experimentar e agir com menos dependencia de regras.',manager:'Ajuste o nivel de detalhe, controle e autonomia a complexidade real da funcao.',personal:'Busque equilibrio entre qualidade e velocidade para evitar tanto retrabalho quanto excesso de analise.'}
};
const valueInfo:any={
 'Religioso / Espiritual':{
  measures:'Importância atribuída a propósito, sentido, coerência com princípios pessoais e percepção de que aquilo que faz precisa ter significado.',
  daily:'No dia a dia, pode aparecer na necessidade de compreender o porquê das atividades e de perceber coerência entre suas responsabilidades e aquilo que considera importante.',
  motivates:'Atividades com propósito claro, sensação de contribuição, coerência entre discurso e prática e ambientes em que seus princípios pessoais possam ser respeitados.',
  attention:'Quando essa necessidade é muito forte, pode haver desconforto em contextos percebidos como sem propósito ou desalinhados com seus princípios.',
  manager:'Trate este resultado apenas como motivador declarado. Ele não mede caráter, ética, qualidade da crença ou adequação religiosa e nunca deve ser usado como critério automático de contratação.',
  personal:'Observe em quais situações o sentido do trabalho aumenta seu envolvimento e diferencie convicções pessoais de expectativas que precisam ser negociadas no ambiente profissional.'
 },
 'Teorico':{
  measures:'Interesse por aprender, compreender, investigar, organizar informações e encontrar explicações antes de chegar a conclusões.',
  daily:'Pode aparecer como necessidade de entender contexto, lógica, funcionamento e critérios das tarefas, além de preferência por decisões fundamentadas.',
  motivates:'Aprendizado, treinamentos, acesso a informações, desafios intelectuais, possibilidade de aprofundar conhecimento e desenvolver domínio técnico.',
  attention:'A busca por mais informações pode, em algumas situações, prolongar análises ou decisões que já dispõem de dados suficientes.',
  manager:'Ofereça contexto, critérios e oportunidades de aprendizado, observando quando mais informação realmente melhora a decisão e quando apenas adia a execução.',
  personal:'Transforme curiosidade em conhecimento aplicado e defina um ponto de suficiência para a análise antes de agir.'
 },
 'Estetico':{
  measures:'Valorização de harmonia, criatividade, experiência, qualidade, organização visual e sensibilidade ao ambiente e à forma de realizar as atividades.',
  daily:'Pode aparecer no cuidado com apresentação, experiência, acabamento, organização e busca de soluções mais agradáveis, criativas ou coerentes.',
  motivates:'Liberdade criativa, ambientes agradáveis, cuidado com qualidade e apresentação, experiências bem construídas e possibilidade de aprimorar entregas.',
  attention:'Pode haver maior desconforto em ambientes percebidos como desorganizados, visualmente descuidados ou excessivamente rígidos, além de risco de elevar demais o padrão antes de concluir.',
  manager:'Considere espaço para criatividade e qualidade de apresentação quando isso fizer sentido para a função, sem transformar preferência estética em exigência universal.',
  personal:'Use sua sensibilidade para melhorar entregas, mas defina critérios objetivos de conclusão para evitar perfeccionismo improdutivo.'
 },
 'Economico':{
  measures:'Valorização de utilidade, eficiência, produtividade, retorno e percepção concreta de resultado. Não significa simplesmente interesse por dinheiro.',
  daily:'Pode aparecer na busca por entender para que algo serve, qual resultado produz, como usar melhor recursos e como tornar processos mais eficientes.',
  motivates:'Metas claras, indicadores, produtividade, reconhecimento por resultado e percepção de que o esforço gera retorno ou melhoria concreta.',
  attention:'Atividades muito abstratas ou com resultado pouco visível podem parecer menos estimulantes; em excesso, existe risco de valorizar apenas o que é imediatamente mensurável.',
  manager:'Dê clareza sobre objetivos, impacto e indicadores relevantes, sem reduzir a contribuição da pessoa somente a números.',
  personal:'Use o foco em resultado como força, lembrando que nem todo valor profissional aparece de forma imediata ou quantitativa.'
 },
 'Social':{
  measures:'Valorização de relações humanas, cooperação, contribuição, ajuda e percepção de impacto positivo sobre outras pessoas.',
  daily:'Pode aparecer em disponibilidade para ajudar, atenção ao clima da equipe, busca por colaboração e satisfação ao perceber que seu trabalho beneficia alguém.',
  motivates:'Trabalho em equipe, reconhecimento da contribuição, contato com pessoas, ajuda mútua, desenvolvimento de outros e percepção de impacto humano.',
  attention:'Pode existir tendência a evitar conflitos, assumir responsabilidades alheias ou colocar necessidades dos outros à frente das próprias em algumas situações.',
  manager:'Valorize contribuição e colaboração, mas preserve clareza de papéis, limites e responsabilidade individual.',
  personal:'Ajude e coopere sem assumir o que pertence aos outros; pratique conversas difíceis quando forem necessárias.'
 },
 'Politico / Lideranca e Influencia':{
  measures:'Valorização de protagonismo, influência sobre decisões, visibilidade, liderança, reconhecimento e possibilidade de direcionar situações.',
  daily:'Pode aparecer no interesse por assumir responsabilidade, participar de decisões, defender ideias, mobilizar pessoas ou ter maior autonomia sobre caminhos e prioridades.',
  motivates:'Oportunidades de responsabilidade, visibilidade, participação em decisões, liderança de iniciativas e possibilidade de influenciar resultados.',
  attention:'Quando muito valorizado, pode haver frustração em contextos com pouca autonomia ou reconhecimento; quando aparece mais baixo, isso não significa ausência de capacidade de liderança.',
  manager:'Não confunda intensidade deste motivador com competência para liderar. Use-o para entender o quanto protagonismo, visibilidade e influência pesam na motivação.',
  personal:'Desenvolva influência com responsabilidade, escuta e clareza de limites, sem usar reconhecimento externo como única medida de sucesso.'
 }
};
function integratedValuesText(values:any[],firstName='A pessoa'){
 if(!values.length)return 'Os motivadores devem ser explorados em conversa e observação de situações reais.';
 const sorted=values.map(([k,v])=>[String(k),Number(v)] as [string,number]).sort((a,b)=>b[1]-a[1]);
 const top=sorted.slice(0,4); const spread=top.length>1?top[0][1]-top[top.length-1][1]:0;
 const names=top.map(([k])=>k);
 if(top.length>=4 && spread<=3)return `Os resultados mostram uma distribuição bastante equilibrada entre ${names.join(', ')}. Isso sugere que a motivação de ${firstName} provavelmente não depende de um único fator, mas da combinação entre esses motivadores. A leitura deve priorizar a forma como eles se complementam no contexto real.`;
 if(top.length>=3 && top[0][1]-top[2][1]<=3)return `Os três motivadores mais presentes — ${names.slice(0,3).join(', ')} — aparecem muito próximos entre si. Em vez de tratar apenas o primeiro como dominante, vale observar como essa combinação influencia escolhas, engajamento e satisfação no trabalho.`;
 return `Os motivadores mais presentes são ${names.slice(0,3).join(', ')}. Eles indicam fatores que podem aumentar interesse e engajamento, mas devem ser interpretados em conjunto com contexto, função e comportamentos observáveis.`;
}
const discColors:any={D:'#d94a45',I:'#f2c94c',S:'#4caf73',C:'#4a7bd0'};
const valueColors=['#6f918b','#c9785d','#8c7bb8','#d8a647','#5d8aa8','#8a9a5b'];
const riasecColors:any={realista:'#c9785d',investigativo:'#4a7bd0',artistico:'#9b6bb3',social:'#4caf73',empreendedor:'#d99a34',convencional:'#6f918b'};
function bar(label:string,value:number,color='#174e4a'){return `<div class="barrow"><div class="barlabel"><span>${escapeHtml(label)}</span><b>${Math.round(value)}%</b></div><div class="track"><div class="fill" style="width:${Math.max(0,Math.min(100,value))}%;background:${color}"></div></div></div>`}
function discOverview(r:any){
 const vals:any={D:Number(r?.disc?.D||0),I:Number(r?.disc?.I||0),S:Number(r?.disc?.S||0),C:Number(r?.disc?.C||0)};
 const labels:any={D:'Dominante',I:'Influente',S:'Estável',C:'Conforme'};
 const cards=['D','I','S','C'].map(k=>`<div class="disc-card ${k.toLowerCase()}" style="background:${discColors[k]}"><div><div class="letter">${k}</div><div class="disc-name">${labels[k]}</div></div><div class="disc-pct">${Math.round(vals[k])}%</div></div>`).join('');
 const comp=['D','I','S','C'].map(k=>`<span style="width:${Math.max(0,vals[k])}%;background:${discColors[k]}"></span>`).join('');
 const legend=['D','I','S','C'].map(k=>`<span><i style="background:${discColors[k]}"></i>${labels[k]}</span>`).join('');
 return `<div class="disc-grid">${cards}</div><div class="composition">${comp}</div><div class="legend">${legend}</div>`;
}
function vocCoverGraphic(r:any){
 if(!r?.interests)return '<div class="callout">Resultado de uma versão anterior do teste vocacional. O histórico original foi preservado.</div>';
 const top=(r?.topInterests||Object.entries(r.interests).sort((a:any,b:any)=>Number(b[1])-Number(a[1])).slice(0,3).map(([k])=>k)) as string[];
 return `<div class="chart-title">Código predominante</div><div style="font-size:42px;font-weight:950;color:#174e4a;letter-spacing:.08em">${escapeHtml(r?.riasecCode||top.map(k=>vocInterestInfo[k]?.letter||'').join(''))}</div><div class="tag-list">${top.map(k=>`<span class="tag" style="border-color:${riasecColors[k]||'#6f918b'}">${escapeHtml(vocInterestInfo[k]?.label||k)}</span>`).join('')}</div>`;
}
function behaviorSummaryRows(r:any,personName:string){
 if(!r)return'';
 const disc=Object.entries(r.disc||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1])) as [string,number][];
 const values=Object.entries(r.values||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1])) as [string,number][];
 const primary=String(r.discPrimary||disc[0]?.[0]||'');
 const secondary=String(r.discSecondary||disc[1]?.[0]||'');
 const pVal=Number((r.disc||{})[primary]||0), sVal=Number((r.disc||{})[secondary]||0);
 const balanced=r?.discPattern==='equilibrado' || (r?.version!==3 && Math.abs(pVal-sVal)<=4 && disc.length>2 && Math.abs(Number(disc[0]?.[1]||0)-Number(disc[3]?.[1]||0))<=12);
 const firstName=escapeHtml(String(personName||'A pessoa').trim().split(/\s+/)[0]||'A pessoa');
 const profileMap:any={
  D:'objetivo, direto, orientado a desafios e com maior tendência a agir com rapidez',
  I:'comunicativo, relacional, persuasivo e com maior tendência a envolver outras pessoas',
  S:'constante, cooperativo, paciente e atento à estabilidade nas relações e atividades',
  C:'cuidadoso, analítico, organizado e atento à qualidade, critérios e detalhes'
 };
 const lowMap:any={D:'cautela e cooperação',I:'comunicação mais seletiva e reservada',S:'adaptação a mudanças e variedade',C:'praticidade e menor dependência de regras'};
 const discPhrase=balanced
   ?`O perfil aparece relativamente equilibrado, com diferenças pequenas entre as dimensões. Ainda assim, há leve predominância de <b>${discInfo[primary]?.name||primary} (${Math.round(pVal)}%)</b> e <b>${discInfo[secondary]?.name||secondary} (${Math.round(sVal)}%)</b>.`
   :`O resultado apresenta maior predominância de <b>${discInfo[primary]?.name||primary} (${Math.round(pVal)}%)</b> e <b>${discInfo[secondary]?.name||secondary} (${Math.round(sVal)}%)</b>.`;
 const summaryText=`${discPhrase} De forma geral, ${firstName} tende a apresentar um comportamento ${profileMap[primary]||'compatível com as tendências predominantes'}${secondary?`, combinado com traços de ${profileMap[secondary]||discInfo[secondary]?.name||secondary}`:''}.`;
 const bullets:string[]=[];
 const add=(x:string)=>{if(x&&!bullets.includes(x))bullets.push(x)};
 if(primary==='S'||secondary==='S')add('manter constância e estabilidade nas atividades');
 if(primary==='C'||secondary==='C')add('analisar antes de concluir e valorizar organização, qualidade e clareza');
 if(primary==='D'||secondary==='D')add('agir com iniciativa, objetividade e foco em resultado quando o contexto exige');
 if(primary==='I'||secondary==='I')add('estabelecer conexão por meio da comunicação e do relacionamento');
 const c=r.communication||{};
 if(Number(c.introversion||0)>=55)add('preferir reflexão e interações mais seletivas antes de se posicionar');
 if(Number(c.extroversion||0)>=55)add('processar ideias com maior interação e troca com outras pessoas');
 const workEntries=Object.values(r.work||{}) as any[];
 for(const x of workEntries){
   const l=Number(x.left||0), rr=Number(x.right||0);
   if(l>=60)add(`demonstrar preferência por ${String(x.labels?.[0]||'').toLowerCase()}`);
   else if(rr>=60)add(`demonstrar preferência por ${String(x.labels?.[1]||'').toLowerCase()}`);
 }
 while(bullets.length>7)bullets.pop();
 const ext=Number(c.extroversion||0), intro=Number(c.introversion||0);
 let commLabel='Ambivertido';
 if(intro>=65)commLabel='Introvertido'; else if(intro>=55)commLabel='Levemente introvertido'; else if(ext>=65)commLabel='Extrovertido'; else if(ext>=55)commLabel='Levemente extrovertido';
 const commText=intro>=55
   ?'Isso indica preferência por reflexão, interações mais seletivas e maior processamento interno antes da exposição. Esse resultado não representa dificuldade de comunicação, mas uma preferência de interação.'
   :ext>=55
   ?'Isso indica maior preferência por troca, expressão e processamento de ideias em interação. Esse resultado descreve estilo de interação e não mede qualidade da comunicação.'
   :'Isso indica equilíbrio entre momentos de interação e de reserva, com adaptação relativamente maior ao contexto, ao grupo e ao tema.';
 const workLines:string[]=[]; const workBars:string[]=[];
 for(const x of workEntries){
   const l=Number(x.left||0), rr=Number(x.right||0);
   const left=String(x.labels?.[0]||''), right=String(x.labels?.[1]||'');
   const chosen=l>=rr?left:right, value=Math.max(l,rr);
   workLines.push(`<li>${escapeHtml(chosen)}: ${Math.round(value)}%</li>`); workBars.push(bar(chosen,value,'#6f918b'));
 }
 const wa:any=r.work||{};
 const autonomy=Number(wa.autonomia_direcionamento?.left||0), direction=Number(wa.autonomia_direcionamento?.right||0);
 const structure=Number(wa.estrutura_flexibilidade?.left||0), flexibility=Number(wa.estrutura_flexibilidade?.right||0);
 const routine=Number(wa.rotina_variedade?.left||0), variety=Number(wa.rotina_variedade?.right||0);
 const individual=Number(wa.individual_interacao?.left||0), interaction=Number(wa.individual_interacao?.right||0);
 const speed=Number(wa.rapidez_analise?.left||0), analysis=Number(wa.rapidez_analise?.right||0);
 const competition=Number(wa.competicao_cooperacao?.left||0), cooperation=Number(wa.competicao_cooperacao?.right||0);
 let workInterpretation='As preferências de ambiente devem ser lidas em conjunto, pois indicam condições que tendem a facilitar o funcionamento natural da pessoa.';
 if(autonomy>=60 && (routine>=55||structure>=55)) workInterpretation=`Um ponto relevante é a combinação entre necessidade de alguma previsibilidade e preferência por autonomia. ${firstName} tende a responder bem quando entende claramente o objetivo e recebe espaço para conduzir a própria execução.`;
 else if(autonomy>=60) workInterpretation=`${firstName} tende a responder melhor quando os objetivos estão claros e existe espaço para decidir como executar as responsabilidades.`;
 else if(direction>=60) workInterpretation=`${firstName} tende a se beneficiar de expectativas, prioridades e critérios de sucesso bem explicitados, especialmente no início de atividades novas.`;
 else if(analysis>=60) workInterpretation=`A preferência por análise sugere maior conforto quando existe tempo suficiente para compreender informações, critérios e consequências antes de decidir.`;
 else if(interaction>=60) workInterpretation=`A preferência por interação sugere maior conforto em ambientes com troca frequente, colaboração e contato com outras pessoas.`;
 const topValues=values.slice(0,4);
 const motivatorText=integratedValuesText(values,firstName);
 const dev:string[]=[];
 if(Number((r.disc||{}).D||0)<=22)dev.push('fortalecer posicionamento, assertividade e tomada de decisão em situações que exigem rapidez ou informações incompletas');
 if(Number((r.disc||{}).D||0)>=32)dev.push('equilibrar velocidade de decisão com escuta, consulta e consideração do impacto sobre outras pessoas');
 if(Number((r.disc||{}).C||0)>=30 || analysis>=60)dev.push('observar quando a busca por análise, segurança ou qualidade começa a atrasar decisões que já têm informação suficiente');
 if(Number((r.disc||{}).I||0)>=32)dev.push('equilibrar entusiasmo e expressão com escuta ativa, objetividade e confirmação de entendimento');
 if(Number((r.disc||{}).I||0)<=22 || intro>=60)dev.push('praticar exposição de ideias e posicionamento em situações em que sua contribuição precisa aparecer com mais clareza');
 if(Number((r.disc||{}).S||0)>=30 || routine>=60)dev.push('ampliar tolerância a mudanças de prioridade, experimentando pequenas adaptações antes que o cenário esteja totalmente previsível');
 if(cooperation>=60)dev.push('preservar a cooperação sem evitar conversas difíceis ou assumir responsabilidades que pertencem a outras pessoas');
 const uniqueDev=[...new Set(dev)].slice(0,3);
 if(!uniqueDev.length)uniqueDev.push('observar quais comportamentos funcionam bem no contexto atual e quais precisam ser ajustados quando o ambiente muda');
 const conclusion=`O perfil indica uma pessoa com tendência a ${profileMap[primary]||discInfo[primary]?.name||primary}${secondary?` e também a ${profileMap[secondary]||discInfo[secondary]?.name||secondary}`:''}. ${firstName} tende a funcionar melhor quando o contexto oferece ${autonomy>=55?'autonomia compatível com a responsabilidade':'clareza sobre expectativas'}${analysis>=55?', espaço para analisar informações':''}${cooperation>=55?', relações colaborativas':''}${routine>=55?', alguma previsibilidade de rotina':''}.`;
 let html=`<div class="box"><div class="page-kicker">DISC</div><h2>1. Síntese do perfil</h2>${discOverview(r)}<p>${summaryText}</p></div>`;
 html+=`<div class="box"><h2>2. Principais características observadas</h2><p>A avaliação sugere tendência a:</p><ul>${bullets.map(x=>`<li>${escapeHtml(x)};</li>`).join('')}</ul><p>A dimensão menos presente foi <b>${discInfo[String(disc[disc.length-1]?.[0]||'')]?.name||disc[disc.length-1]?.[0]||'-'}</b>, o que pode indicar maior tendência a ${lowMap[String(disc[disc.length-1]?.[0]||'')]||'usar o comportamento complementar com menor frequência'}.</p></div>`;
 html+=`<div class="box"><div class="page-kicker">Comunicação</div><h2>3. Comunicação</h2>${bar('Introversão',intro,'#4a7bd0')}${bar('Extroversão',ext,'#c9785d')}<p>O estilo de comunicação foi classificado como <b>${commLabel}</b>, com <b>${Math.round(intro)}% de introversão</b> e <b>${Math.round(ext)}% de extroversão</b>.</p><p>${commText}</p></div>`;
 html+=`<div class="box"><div class="page-kicker">Ambiente</div><h2>4. Ambiente de trabalho</h2><p>A avaliação mostra maior preferência por:</p>${workBars.join('')}<ul>${workLines.join('')}</ul><p>${workInterpretation}</p></div>`;
 html+=`<div class="box"><div class="page-kicker">Motivadores</div><h2>5. Motivadores</h2><p>Os valores aparecem com maior presença de:</p>${topValues.map(([k,v],idx)=>bar(String(k),Number(v),valueColors[idx%valueColors.length])).join('')}<div class="callout"><b>Leitura integrada:</b> ${escapeHtml(motivatorText)}</div>${topValues.map(([k,v])=>{const i=valueInfo[String(k)]||{};return `<div class="item"><h3>${escapeHtml(String(k))} <span class="score">${Number(v).toFixed(1)}%</span></h3><p><b>O que representa:</b> ${i.measures||''}</p><p><b>Como pode aparecer no dia a dia:</b> ${i.daily||''}</p><p><b>O que tende a motivar:</b> ${i.motivates||''}</p><p><b>Ponto de atenção:</b> ${i.attention||''}</p></div>`}).join('')}</div>`;
 html+=`<div class="box"><h2>6. Pontos de desenvolvimento</h2><p>Alguns aspectos que podem ser observados e desenvolvidos, conforme as demandas reais do contexto:</p><ul>${uniqueDev.map(x=>`<li>${escapeHtml(x)}.</li>`).join('')}</ul></div>`;
 html+=`<div class="box"><h2>7. Conclusão</h2><p>${conclusion}</p><p>Os resultados devem ser utilizados como ferramenta de desenvolvimento e autoconhecimento, e não como definição fixa de personalidade. As tendências devem ser comparadas com comportamentos observados no dia a dia e com as exigências reais da função.</p></div>`;
 return html;
}

function behaviorDetailedRows(r:any,mode:'manager'|'personal'){
 if(!r)return'';
 const disc=Object.entries(r.disc||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1]));
 const values=Object.entries(r.values||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1]));
 const primary=String(r.discPrimary||disc[0]?.[0]||''); const secondary=String(r.discSecondary||disc[1]?.[0]||'');
 const topValues=values.slice(0,3).map(([k])=>k);
 const discIntro=r?.discPattern==='equilibrado' ? `O resultado mostra um perfil combinado entre <b>${discInfo[primary]?.name||primary}</b> e <b>${discInfo[secondary]?.name||secondary}</b>, com diferença pequena entre os dois fatores.` : r?.discPattern==='predominancia_moderada' ? `O resultado mostra predominância moderada de <b>${discInfo[primary]?.name||primary}</b>, com presença próxima de <b>${discInfo[secondary]?.name||secondary}</b>.` : `O resultado mostra maior expressão de <b>${discInfo[primary]?.name||primary}</b>${secondary?` com apoio de <b>${discInfo[secondary]?.name||secondary}</b>`:''}.`;
 let html=`<div class="box"><h2>1. Sintese integrada</h2><p>${discIntro} O estilo de comunicacao foi classificado como <b>${r.communication?.classification||'-'}</b>. Entre os valores mais presentes aparecem <b>${topValues.join(', ')}</b>.</p><div class="callout">${mode==='manager'?'<b>Uso gerencial:</b> trate o resultado como hipotese para orientar entrevista, feedback e desenvolvimento. Confirme sempre com exemplos observaveis.':'<b>Uso pessoal:</b> o objetivo nao e rotular sua personalidade, mas ampliar sua consciencia sobre tendencias e escolhas de comportamento.'}</div></div>`;
 html+=`<div class="box"><div class="page-kicker">DISC</div><h2>2. Perfil Comportamental - DISC</h2><p class="small">Percentuais relativos às 24 escolhas do bloco DISC. A soma é 100% e mostra a composição das escolhas desta avaliação.</p>${discOverview(r)}${disc.map(([k,v]:any)=>bar(`${k} - ${discInfo[k]?.name||k}`,Number(v),discColors[k]||'#174e4a')).join('')}`;
 for(const [k,v0] of disc as any){const v=Number(v0),i=discInfo[k];html+=`<div class="item"><h3>${k} - ${i.name} <span class="score">${v.toFixed(1)}%</span></h3><p><b>O que mede:</b> ${i.measures}</p><p><b>Leitura:</b> ${k===primary?i.high:i.low}</p><p><b>${mode==='manager'?'Aplicacao gerencial':'Desenvolvimento'}:</b> ${mode==='manager'?i.manager:i.personal}</p></div>`}
 html+=`</div>`;
 const c=r.communication||{};html+=`<div class="box"><h2>3. Estilo de Comunicacao</h2><h3>${c.classification||'-'}</h3>${bar('Extroversão',Number(c.extroversion||0),'#c9785d')}${bar('Introversão',Number(c.introversion||0),'#4a7bd0')}<p><b>O que mede:</b> preferencia por exposicao, interacao e processamento social. Nao mede capacidade de comunicacao, inteligencia ou competencia profissional.</p><p><b>Leitura:</b> ${c.classification==='Extrovertido'?'Ha maior preferencia por troca, expressao e interacao como parte do processamento de ideias.':c.classification==='Introvertido'?'Ha maior preferencia por reflexao interna, interacoes mais seletivas e momentos de reserva.':'Ha equilibrio entre interacao e reserva, com maior variacao conforme contexto, grupo e tema.'}</p><p><b>${mode==='manager'?'Aplicacao gerencial':'Desenvolvimento'}:</b> ${mode==='manager'?'Adapte reunioes, feedbacks e canais de comunicacao sem confundir expansividade com engajamento.':'Observe em quais contextos voce se comunica melhor e pratique conscientemente o estilo complementar quando necessario.'}</p></div>`;
 html+=`<div class="box"><h2>4. Valores e Motivadores</h2><p class="small">Percentuais relativos entre os seis valores. Eles representam prioridades e motivadores declarados, nao carater, etica ou merito profissional.</p>${values.map(([k,v]:any,idx:number)=>bar(k,Number(v),valueColors[idx%valueColors.length])).join('')}`;
 html+=`<div class="callout"><b>Leitura integrada dos motivadores:</b> ${escapeHtml(integratedValuesText(values,'a pessoa'))}</div>`;
 for(const [k,v0] of values as any){const v=Number(v0),i=valueInfo[k]||{};html+=`<div class="item"><h3>${escapeHtml(String(k))} <span class="score">${v.toFixed(1)}%</span></h3><p><b>O que representa:</b> ${i.measures||''}</p><p><b>Como pode aparecer no dia a dia:</b> ${i.daily||''}</p><p><b>O que tende a motivar:</b> ${i.motivates||''}</p><p><b>Ponto de atenção:</b> ${i.attention||''}</p><p><b>${mode==='manager'?'Aplicação gerencial':'Reflexão de desenvolvimento'}:</b> ${mode==='manager'?i.manager:i.personal}</p></div>`}
 html+=`</div>`;
 html+=`<div class="box"><h2>5. Preferencias no Ambiente de Trabalho</h2><p class="small">Cada linha e um continuo. Nao existe lado certo ou errado; o resultado indica preferencia relativa.</p>`;
 for(const x of Object.values(r.work||{}) as any[]){html+=`<div class="item"><h3>${x.labels?.[0]} x ${x.labels?.[1]}</h3>${bar(x.labels?.[0]||'',Number(x.left||0))}${bar(x.labels?.[1]||'',Number(x.right||0))}</div>`}
 html+=`</div>`;
 if(mode==='manager')html+=`<div class="box"><h2>6. Perguntas para aprofundar</h2><ul><li>Conte uma situacao em que precisou decidir sob pressao. Como chegou a decisao?</li><li>Que tipo de ambiente faz voce produzir melhor? O que costuma atrapalhar?</li><li>Como prefere receber uma orientacao dificil ou um feedback corretivo?</li><li>Qual tipo de resultado ou reconhecimento mais aumenta sua motivacao?</li><li>Que comportamento seu ja precisou ser ajustado para trabalhar melhor com pessoas diferentes?</li></ul></div>`;
 else html+=`<div class="box"><h2>6. Plano de desenvolvimento</h2><ul><li><b>Manter:</b> escolha uma tendencia que ja produz bons resultados e defina como usa-la sem excesso.</li><li><b>Desenvolver:</b> escolha um comportamento complementar que aumentaria sua flexibilidade.</li><li><b>Pratica:</b> defina uma acao pequena e observavel para repetir durante 30 dias.</li><li><b>Evidencia:</b> acompanhe por feedback, qualidade, prazo, autonomia ou reducao de retrabalho.</li></ul></div>`;
 return html;
}
const vocInterestInfo:any={
 realista:{label:'Realista / Pratico',letter:'R',desc:'Interesse por execucao concreta, operacao, ferramentas, campo, producao e solucoes praticas.',families:['Engenharias e areas tecnicas','Logistica, operacoes e manutencao','Arquitetura, construcao e producao','Agronegocio e atividades de campo'],courses:['Engenharias','Cursos tecnicos industriais','Logistica','Arquitetura e Urbanismo','Agronomia']},
 investigativo:{label:'Investigativo',letter:'I',desc:'Interesse por analise, pesquisa, diagnostico, ciencia, dados, tecnologia e resolucao de problemas complexos.',families:['Tecnologia e dados','Pesquisa e ciencias','Saude diagnostica e investigativa','Analise economica e quantitativa'],courses:['Ciencia da Computacao','Ciencia de Dados','Biomedicina','Farmacia','Estatistica','Economia']},
 artistico:{label:'Artistico / Criativo',letter:'A',desc:'Interesse por criacao, expressao, comunicacao, design, linguagem, estetica e novas possibilidades.',families:['Comunicacao e marketing','Design e experiencia','Artes e producao cultural','Conteudo e industrias criativas'],courses:['Publicidade e Propaganda','Design','Marketing','Jornalismo','Arquitetura e Urbanismo','Artes Visuais']},
 social:{label:'Social',letter:'S',desc:'Interesse por ensinar, orientar, cuidar, desenvolver pessoas e gerar impacto humano direto.',families:['Educacao e desenvolvimento','Psicologia e comportamento humano','Recursos Humanos','Saude e cuidado','Projetos sociais'],courses:['Psicologia','Pedagogia','Recursos Humanos','Enfermagem','Servico Social','Fisioterapia']},
 empreendedor:{label:'Empreendedor',letter:'E',desc:'Interesse por lideranca, negociacao, vendas, influencia, gestao, oportunidades e tomada de decisao.',families:['Administracao e gestao','Comercial e vendas','Empreendedorismo e negocios','Direito e negociacao','Gestao de projetos'],courses:['Administracao','Gestao Comercial','Marketing','Direito','Economia','Gestao de Projetos']},
 convencional:{label:'Convencional / Organizacional',letter:'C',desc:'Interesse por organizacao, controles, processos, dados estruturados, planejamento e precisao.',families:['Administracao e operacoes','Financas e controladoria','Contabilidade','Planejamento e processos','Compliance e qualidade'],courses:['Administracao','Ciencias Contabeis','Gestao Financeira','Processos Gerenciais','Logistica','Economia']}
};
const vocSkillLabels:any={practical:'Pratica / execucao',analytical:'Analise e raciocinio',creative:'Criatividade',interpersonal:'Relacionamento e escuta',influence:'Influencia e lideranca',organization:'Organizacao e controle'};
const vocValueLabels:any={stability:'Estabilidade',income:'Remuneracao',purpose:'Proposito',recognition:'Reconhecimento',autonomy:'Autonomia',creativity:'Criatividade',learning:'Aprendizado',leadership:'Lideranca',balance:'Equilibrio de vida',impact:'Impacto social'};
const interestSkillMap:any={realista:'practical',investigativo:'analytical',artistico:'creative',social:'interpersonal',empreendedor:'influence',convencional:'organization'};
function vocRows(r:any){
 if(!r?.interests){const legacyLabels:any={pratico:'Pratico',investigativo:'Investigativo',criativo:'Criativo',social:'Social',empreendedor:'Empreendedor',organizacional:'Organizacional'};const legacy=Object.entries(r||{}).filter(([,v])=>typeof v==='number').sort((a:any,b:any)=>Number(b[1])-Number(a[1]));return `<div class="box"><h2>Resultado de versao anterior</h2><p>Esta avaliacao foi respondida antes da ampliacao do teste vocacional. O resultado original foi preservado.</p><table><tbody>${legacy.map(([k,v])=>`<tr><td>${legacyLabels[k]||k}</td><td>${v}/25</td></tr>`).join('')}</tbody></table></div>`;}
 const interests=Object.entries(r?.interests||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1]));
 const top=(r?.topInterests?.length?r.topInterests:interests.slice(0,3).map(([k])=>k)) as string[];
 const code=r?.riasecCode||top.map(k=>vocInterestInfo[k]?.letter||'').join('');
 const skills=Object.entries(r?.skills||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1]));
 const careerValues=Object.entries(r?.careerValues||{}).sort((a:any,b:any)=>Number(b[1])-Number(a[1]));
 const topFamilies=[...new Set(top.flatMap(k=>vocInterestInfo[k]?.families||[]))].slice(0,10);
 const topCourses=[...new Set(top.flatMap(k=>vocInterestInfo[k]?.courses||[]))].slice(0,12);
 let html=`<div class="box"><h2>1. Resumo do perfil vocacional</h2><p>Seu codigo de interesses predominantes e <b>${code||'-'}</b>, formado por ${top.map(k=>`<b>${vocInterestInfo[k]?.label||k}</b>`).join(' + ')}.</p><p>Esse codigo nao determina uma profissao. Ele organiza os tipos de atividade que mais despertaram interesse nesta avaliacao e serve como ponto de partida para explorar cursos, ocupacoes e ambientes profissionais.</p><div class="callout"><b>Leitura importante:</b> interesse, habilidade percebida e valor de carreira sao dimensoes diferentes. Uma boa escolha costuma considerar o encontro entre as tres, alem de realidade de mercado, formacao necessaria e experiencias concretas.</div></div>`;
 html+=`<div class="box"><h2>2. Mapa de interesses - RIASEC</h2><p class="small">As porcentagens indicam intensidade de interesse declarada em cada grupo, de 0% a 100%.</p>${interests.map(([k,v]:any)=>bar(vocInterestInfo[k]?.label||k,Number(v),riasecColors[k]||'#174e4a')).join('')}`;
 for(const [k,v0] of interests as any){const i=vocInterestInfo[k];html+=`<div class="item"><h3>${i?.label||k} <span class="score">${Number(v0).toFixed(0)}%</span></h3><p>${i?.desc||''}</p>${top.includes(k)?'<p><b>Entre seus interesses predominantes.</b></p>':''}</div>`}
 html+=`</div>`;
 html+=`<div class="box"><h2>3. Preferencias de trabalho</h2><p class="small">Cada linha representa um continuo. O objetivo e mostrar em que tipo de ambiente voce tende a se sentir mais confortavel, sem indicar certo ou errado.</p>`;
 for(const x of Object.values(r?.preferences||{}) as any[]){html+=`<div class="item"><h3>${x.labels?.[0]} x ${x.labels?.[1]}</h3>${bar(x.labels?.[0]||'',Number(x.left||0))}${bar(x.labels?.[1]||'',Number(x.right||0))}</div>`}
 html+=`</div>`;
 html+=`<div class="box"><h2>4. Habilidades percebidas</h2><p class="small">Mostra onde voce percebe maior facilidade hoje. Nao substitui avaliacao de competencia, desempenho ou experiencia pratica.</p>${skills.map(([k,v]:any,idx:number)=>bar(vocSkillLabels[k]||k,Number(v),valueColors[idx%valueColors.length])).join('')}</div>`;
 html+=`<div class="box"><h2>5. Valores de carreira</h2><p class="small">O que tende a pesar mais na sua satisfacao profissional. Como cada valor foi avaliado individualmente, use o resultado como ponto de reflexao, nao como ranking definitivo.</p>${careerValues.map(([k,v]:any,idx:number)=>bar(vocValueLabels[k]||k,Number(v),valueColors[idx%valueColors.length])).join('')}<p><b>Valores mais destacados:</b> ${careerValues.slice(0,4).map(([k])=>vocValueLabels[k]||k).join(', ')}.</p></div>`;
 html+=`<div class="box"><h2>6. Cruzamento entre interesse e habilidade percebida</h2><table><thead><tr><th>Area</th><th>Interesse</th><th>Habilidade relacionada</th><th>Leitura</th></tr></thead><tbody>${top.map(k=>{const sk=interestSkillMap[k];const iv=Number((r?.interests||{})[k]||0),sv=Number((r?.skills||{})[sk]||0);const reading=iv>=65&&sv>=65?'Interesse e facilidade percebida aparecem juntos. Vale explorar com profundidade.':iv>=65&&sv<65?'Ha interesse relevante, mas a habilidade pode precisar de pratica e desenvolvimento.':iv<65&&sv>=65?'Existe facilidade percebida, embora o interesse nao esteja entre os mais altos.':'Area para explorar sem conclusoes precipitadas.';return `<tr><td>${vocInterestInfo[k]?.label||k}</td><td>${iv}%</td><td>${vocSkillLabels[sk]||sk}: ${sv}%</td><td>${reading}</td></tr>`}).join('')}</tbody></table></div>`;
 html+=`<div class="box"><h2>7. Familias profissionais para investigar</h2><p>Com base nos interesses predominantes, estas familias merecem pesquisa. Elas nao representam indicacao automatica de carreira.</p><ul>${topFamilies.map(x=>`<li>${x}</li>`).join('')}</ul></div>`;
 html+=`<div class="box"><h2>8. Cursos e formacoes para explorar</h2><p>Algumas formacoes relacionadas aos grupos de interesse mais altos:</p><ul>${topCourses.map(x=>`<li>${x}</li>`).join('')}</ul><p class="small">Antes de decidir, pesquise grade curricular, rotina real da profissao, possibilidades de atuacao, exigencias de formacao e mercado na regiao em que pretende trabalhar.</p></div>`;
 const prefs=Object.values(r?.preferences||{}) as any[];
 const strongPrefs=prefs.map(x=>Number(x.left||0)>=60?x.labels?.[0]:Number(x.right||0)>=60?x.labels?.[1]:'equilibrio').filter(x=>x&&x!=='equilibrio');
 html+=`<div class="box"><h2>9. Ambiente profissional que pode favorecer voce</h2><p>As suas respostas sugerem maior preferencia por: <b>${strongPrefs.length?strongPrefs.join(', '):'ambientes com equilibrio entre diferentes formas de trabalho'}</b>.</p><p>Use isso para investigar a rotina concreta das profissoes. Duas pessoas na mesma carreira podem trabalhar em ambientes muito diferentes.</p></div>`;
 html+=`<div class="box"><h2>10. Perguntas de reflexao</h2><ul><li>Quais dessas areas eu gostaria de experimentar na pratica antes de escolher?</li><li>Quais atividades me fazem perder a nocao do tempo de forma positiva?</li><li>Em quais materias, projetos ou trabalhos eu ja tive satisfacao real?</li><li>O que pesa mais para mim: interesse pelo tema, rotina de trabalho, remuneracao, estabilidade ou impacto?</li><li>Que habilidade eu estaria disposto a desenvolver por alguns anos?</li><li>Quais profissionais dessas areas eu poderia entrevistar para conhecer a rotina real?</li></ul></div>`;
 html+=`<div class="box"><h2>11. Proximos passos</h2><ol><li>Escolha de 3 a 5 familias profissionais deste relatorio.</li><li>Pesquise pelo menos dois cursos ou ocupacoes dentro de cada familia.</li><li>Converse com profissionais que atuam nessas areas.</li><li>Busque experiencias curtas: cursos introdutorios, visitas, projetos, voluntariado ou atividades praticas.</li><li>Depois das experiencias, reveja o que aumentou ou diminuiu seu interesse.</li></ol></div>`;
 return html;
}
function escapeHtml(s:string){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'} as any)[c])}
