'use client';
import {useEffect,useMemo,useState} from 'react'; import {lifeAreas} from '@/lib/life-wheel';
type Person={id:string,full_name:string,email?:string,phone?:string,notes?:string};
type Wheel={id:string,person_id:string,token:string,status:string,created_at:string,completed_at?:string,result?:any,people?:Person};
export default function LifeWheelAdmin(){
 const [people,setPeople]=useState<Person[]>([]),[wheels,setWheels]=useState<Wheel[]>([]),[selected,setSelected]=useState<string>(''),[link,setLink]=useState('');
 const [form,setForm]=useState({full_name:'',email:'',phone:'',notes:''});
 async function load(){const [p,w]=await Promise.all([fetch('/api/people',{cache:'no-store'}),fetch('/api/life-wheels',{cache:'no-store'})]);if(p.ok)setPeople(await p.json());if(w.ok)setWheels(await w.json())}
 useEffect(()=>{load()},[]);
 async function addPerson(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/people',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)return alert(d.error||'Erro');setForm({full_name:'',email:'',phone:'',notes:''});setSelected(d.id);await load()}
 async function newWheel(){if(!selected)return alert('Selecione uma pessoa.');const r=await fetch('/api/life-wheels',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({person_id:selected})});const d=await r.json();if(!r.ok)return alert(d.error||'Erro');setLink(d.url);await load()}
 const person=people.find(p=>p.id===selected);const history=useMemo(()=>wheels.filter(w=>w.person_id===selected).sort((a,b)=>new Date(b.completed_at||b.created_at).getTime()-new Date(a.completed_at||a.created_at).getTime()),[wheels,selected]);
 function copy(){navigator.clipboard.writeText(link).then(()=>alert('Link copiado.')).catch(()=>window.prompt('Copie o link:',link))}
 return <div className="admin-shell"><aside className="sidebar"><div className="sidebar-brand"><div className="brand-mark">PV</div><div><b>Perfil & Vocacional</b><small>Gestão de avaliações</small></div></div><nav className="side-nav"><a className="side-link" href="/admin"><span>⌂</span>Dashboard</a><a className="side-link active" href="/admin/life-wheel"><span>◉</span>Roda da Vida</a></nav><div className="sidebar-note"><span className="dot-live"/>Módulo de acompanhamento</div></aside><main className="admin-main"><header className="page-head"><div><p className="eyebrow">MÓDULO INDEPENDENTE</p><h1>Roda da Vida</h1><p className="muted">Cadastre pessoas, gere novas avaliações e acompanhe a evolução ao longo do tempo.</p></div><a href="/admin" className="btn btn-ghost">← Voltar ao painel</a></header>
 <section className="grid grid-2"><div className="card"><div className="section-head"><div><p className="eyebrow">PESSOAS</p><h2>Novo cadastro</h2></div></div><form onSubmit={addPerson} className="grid"><div><label className="label">Nome completo</label><input className="input" required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></div><div><label className="label">E-mail</label><input className="input" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><label className="label">Telefone</label><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><label className="label">Observações</label><textarea className="input" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><button className="btn btn-primary">Cadastrar pessoa</button></form></div>
 <div className="card"><div className="section-head"><div><p className="eyebrow">NOVA RODA</p><h2>Gerar acompanhamento</h2></div></div><label className="label">Pessoa</label><select className="input" value={selected} onChange={e=>{setSelected(e.target.value);setLink('')}}><option value="">Selecione...</option>{people.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select><button className="btn btn-primary" style={{marginTop:14}} onClick={newWheel}>Gerar link individual</button>{link&&<div className="link-success" style={{marginTop:16}}><div><small>LINK DA RODA DA VIDA</small><div className="generated-link">{link}</div></div><button className="btn btn-copy" onClick={copy}>⧉ Copiar link</button></div>}</div></section>
 {person&&<section className="card" style={{marginTop:22}}><div className="section-head"><div><p className="eyebrow">HISTÓRICO</p><h2>{person.full_name}</h2><p className="muted">Cada nova Roda da Vida fica registrada e pode ser comparada com a anterior.</p></div></div>{history.length===0?<p className="muted">Nenhuma Roda da Vida criada para esta pessoa.</p>:<div className="table-wrap"><table><thead><tr><th>Data</th><th>Status</th><th>Média atual</th><th>Ações</th></tr></thead><tbody>{history.map((w,i)=><tr key={w.id}><td>{new Date(w.completed_at||w.created_at).toLocaleDateString('pt-BR')}</td><td><span className="badge">{w.status==='completed'?'Concluída':w.status==='started'?'Iniciada':'Pendente'}</span></td><td>{w.result?.average!=null?`${w.result.average}/10`:'-'}</td><td>{w.status==='completed'?<button className="btn btn-primary" onClick={()=>openLifeReport(w,history[i+1])}>Abrir relatório / PDF</button>:<span className="muted">Aguardando resposta</span>}</td></tr>)}</tbody></table></div>}</section>}
 {wheels.some(w=>w.status==='completed')&&<section className="card" style={{marginTop:22}}><div className="section-head"><div><p className="eyebrow">RELATÓRIOS</p><h2>Relatórios recentes da Roda da Vida</h2><p className="muted">Acesse diretamente os resultados concluídos, mesmo sem selecionar uma pessoa acima.</p></div></div><div className="table-wrap"><table><thead><tr><th>Pessoa</th><th>Data</th><th>Média</th><th>Ação</th></tr></thead><tbody>{wheels.filter(w=>w.status==='completed').slice(0,10).map(w=>{const personHistory=wheels.filter(x=>x.person_id===w.person_id&&x.status==='completed').sort((a,b)=>new Date(b.completed_at||b.created_at).getTime()-new Date(a.completed_at||a.created_at).getTime());const idx=personHistory.findIndex(x=>x.id===w.id);const prev=idx>=0?personHistory[idx+1]:undefined;return <tr key={`report-${w.id}`}><td>{w.people?.full_name||'Pessoa'}</td><td>{new Date(w.completed_at||w.created_at).toLocaleDateString('pt-BR')}</td><td>{w.result?.average!=null?`${w.result.average}/10`:'-'}</td><td><button className="btn btn-primary" onClick={()=>openLifeReport(w,prev)}>Abrir relatório / PDF</button></td></tr>})}</tbody></table></div></section>}
 </main></div>
}
function polygonPoints(values:number[],cx=210,cy=210,r=150){return values.map((v,i)=>{const a=-Math.PI/2+(Math.PI*2*i/values.length);const rr=r*(v/10);return `${cx+Math.cos(a)*rr},${cy+Math.sin(a)*rr}`}).join(' ')}
function wheelSvg(result:any,previous?:any){const vals=lifeAreas.map(([k])=>Number(result?.areas?.[k]?.current||0));const prev=previous?lifeAreas.map(([k])=>Number(previous?.areas?.[k]?.current||0)):null;let grid='';for(let g=2;g<=10;g+=2)grid+=`<polygon points="${polygonPoints(Array(12).fill(g))}" fill="none" stroke="#d9e2df" stroke-width="1"/>`;let axes='';lifeAreas.forEach(([,label],i)=>{const a=-Math.PI/2+(Math.PI*2*i/12);const x=210+Math.cos(a)*150,y=210+Math.sin(a)*150;const tx=210+Math.cos(a)*184,ty=210+Math.sin(a)*184;axes+=`<line x1="210" y1="210" x2="${x}" y2="${y}" stroke="#e5e9e7"/><text x="${tx}" y="${ty}" font-size="10" text-anchor="middle" dominant-baseline="middle">${label.replace('&','&amp;')}</text>`});return `<svg viewBox="0 0 420 420" width="100%" style="max-width:620px">${grid}${axes}${prev?`<polygon points="${polygonPoints(prev)}" fill="rgba(201,120,93,.08)" stroke="#c9785d" stroke-width="3"/>`:''}<polygon points="${polygonPoints(vals)}" fill="rgba(23,78,74,.12)" stroke="#174e4a" stroke-width="4"/></svg>`}
function openLifeReport(w:Wheel,prev?:Wheel){
 const r=w.result||{},p=prev?.result;
 const priorities=((r.priorities||[]) as any[]).length?(r.priorities as any[]):lifeAreas.map(([k,label])=>({key:k,label,current:Number(r.areas?.[k]?.current??10)})).filter(x=>x.current<=6).sort((a,b)=>a.current-b.current);
 const date=new Date(w.completed_at||w.created_at).toLocaleDateString('pt-BR');
 const rows=lifeAreas.map(([k,label])=>{const a=r.areas?.[k]||{};const b=p?.areas?.[k];const delta=b?Number(a.current)-Number(b.current):null;return `<tr><td>${label}</td><td>${a.current??'-'}</td><td>${b?.current??'-'}</td><td>${delta==null?'-':delta>0?`+${delta}`:delta}</td></tr>`}).join('');
 const plan=priorities.map((x:any)=>`<div class="plan"><h3>${x.label}</h3><p><b>Situação atual:</b> ${x.current}/10</p><p><b>Meta desejada:</b> ______ /10</p><p><b>O que quero melhorar nesta área:</b></p><div class="line"></div><div class="line"></div><p><b>Primeira ação concreta:</b></p><div class="line"></div><div class="line"></div><p><b>Prazo:</b> ____________________</p><p><b>Como vou perceber que avancei:</b></p><div class="line"></div><div class="line"></div><p><b>Observações:</b></p><div class="line"></div></div>`).join('')||'<p>Nenhuma área ficou com nota de 0 a 6 nesta avaliação. Se desejar, escolha manualmente uma área para desenvolvimento e registre um plano de ação.</p>';
 const win=window.open('','_blank');if(!win)return;
 win.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Roda da Vida - ${w.people?.full_name||''}</title><style>@page{size:A4 portrait;margin:12mm}*{box-sizing:border-box;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}body{font-family:Arial,sans-serif;color:#26312f;margin:0}.toolbar{position:sticky;top:0;background:#fff;padding:10px 0;border-bottom:1px solid #ddd;display:flex;gap:8px;z-index:2}.btn{padding:10px 14px;border:0;border-radius:9px;background:#174e4a;color:#fff;font-weight:700}h1{color:#174e4a;margin-bottom:4px}h2{color:#174e4a;margin-top:28px}.muted{color:#6d7774}.box{break-inside:avoid;margin:16px 0}.wheel{text-align:center}.legend{display:flex;gap:20px;justify-content:center;font-size:12px}.dot{display:inline-block;width:12px;height:4px;margin-right:5px;vertical-align:middle}.current{background:#174e4a}.previous{background:#c9785d}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}.plan{border:1px solid #cfd8d5;border-radius:12px;padding:14px;margin:14px 0;break-inside:avoid}.line{height:24px;border-bottom:1px solid #b8c1be}.note{background:#f2f6f5;border-radius:12px;padding:12px}@media print{.toolbar{display:none}.plan{page-break-inside:avoid}}</style></head><body><div class="toolbar"><button class="btn" onclick="window.print()">Salvar em PDF / Imprimir</button></div><h1>Roda da Vida</h1><p class="muted"><b>${w.people?.full_name||''}</b> • ${date}</p><div class="note">A Roda da Vida representa como a pessoa percebe cada área da própria vida neste momento. Não existe nota certa ou errada.</div><div class="box wheel"><h2>Visão geral</h2>${wheelSvg(r,p)}<div class="legend"><span><i class="dot current"></i>Atual</span>${p?'<span><i class="dot previous"></i>Anterior</span>':''}</div></div><div class="box"><h2>Notas e evolução</h2><table><thead><tr><th>Área</th><th>Hoje</th><th>Anterior</th><th>Evolução</th></tr></thead><tbody>${rows}</tbody></table></div><div class="box"><h2>Áreas que merecem atenção</h2><p class="muted">Nesta versão, entram automaticamente no plano as áreas avaliadas de 0 a 6.</p><p>${priorities.length?priorities.map((x:any)=>`${x.label} (${x.current}/10)`).join(' • '):'Nenhuma área ficou entre 0 e 6.'}</p></div><div class="box"><h2>Plano de ação</h2><p class="muted">Use os campos abaixo para transformar as áreas de atenção em ações práticas.</p>${plan}</div></body></html>`);
 win.document.close();
}
